---
sidebar: sidebar 
permalink: qsg.html 
keywords: QSG, ONTAP tools for VMware vSphere, Quick start guide, Installing 
summary: Proporciona instrucciones para poner en marcha e inicializar herramientas de ONTAP para VMware vSphere. 
---
= Herramientas de ONTAP para VMware vSphere Quick Start
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las herramientas de ONTAP para VMware vSphere son un único complemento vCenter Server que incluye herramientas ONTAP, proveedores VASA y extensiones de adaptador de replicación de almacenamiento (SRA). Se recomiendan las herramientas de ONTAP para todos los entornos de ONTAP vSphere, ya que configuran los ajustes del host ESXi y aprovisionan el almacenamiento de ONTAP mediante prácticas recomendadas. El proveedor VASA es necesario para el soporte de volúmenes virtuales (vVols) y el SRA funciona conjuntamente con el administrador de recuperación del sitio de VMware.



== Preparación de la instalación

Pone en marcha el complemento como dispositivo virtual, lo que reduce el esfuerzo de instalar y registrar cada producto por separado en vCenter Server.



=== Requisitos de puesta en marcha

Las herramientas de ONTAP se pueden usar con un dispositivo virtual de VMware vCenter Server (vcsa). Debe implementar las herramientas de ONTAP en una vSphere compatible que incluya el sistema ESXi.

Los requisitos de tamaño mínimo para espacio y host son los siguientes:

[cols="25,75"]
|===
| *Sistema* | *Requisitos mínimos* 


| Espacio | 2.1 GB para instalaciones con thin provisioning, 54.0 GB para instalaciones con thick-Provisioning 


| Ajuste de tamaño del host | Memoria recomendada: 12 GB, CPU recomendadas: 2 
|===
Debe tener en cuenta las siguientes licencias:

[cols="25,75"]
|===
| *Licencia* | *Descripción* 


| SnapMirror | (Opcional) necesario para realizar operaciones de conmutación al nodo de respaldo para el SRA y el proveedor VASA si se usa la replicación de vVols. 


| FlexClone | (Opcional) necesario para realizar operaciones de conmutación al nodo de respaldo de prueba para el SRA y para las operaciones vVols del proveedor VASA. 
|===
Las herramientas de ONTAP utilizan los siguientes puertos TCP bidireccionales predeterminados:

|===


| *Requisitos adicionales* | * Columna Descripción* 


 a| 
9083
 a| 
Cuando se encuentra habilitada, tanto el proveedor VASA como el adaptador de replicación de almacenamiento (SRA) utilizan este puerto para comunicarse con vCenter Server. Este puerto también es necesario para obtener los ajustes de TCP/IP. Este puerto se utiliza para descargar el paquete de soporte VP, acceder a la interfaz de usuario Web-CLI y la comunicación de la ruta de control de VMware a VP.



 a| 
443
 a| 
Según la forma en que haya configurado sus credenciales, VMware vCenter Server y los sistemas de almacenamiento escuchan las comunicaciones seguras en este puerto. El puerto se utiliza en la arquitectura de comunicación cliente-servidor. El puerto 443 está habilitado de manera predeterminada para conexiones seguras. El cliente, que puede ser cualquier cliente de automatización que utilice la API de REST, inicia la conexión con el servidor y los puntos finales intercambian datos.



 a| 
8143
 a| 
Las herramientas de ONTAP escuchan las comunicaciones seguras en este puerto. El puerto se utiliza en la arquitectura de comunicación cliente-servidor. El cliente, que puede ser cualquier cliente de automatización que utilice la API de REST, inicia la conexión con el servidor y los puntos finales intercambian datos. Este puerto está habilitado para los servicios de herramientas de ONTAP y para exportar los registros del servidor de herramientas de ONTAP. La página register.html está alojada en este puerto. El Swagger DE REST queda expuesto en este puerto.



 a| 
8443
 a| 
Este puerto se usa para herramientas de ONTAP para el servicio del complemento de VMware vSphere.

|===
Requisitos mínimos de almacenamiento y aplicaciones:

|===
| *Almacenamiento, host y aplicaciones* | *Requisitos de la versión* 


| ONTAP | ONTAP 9,7, 9.8P1 o posterior. 


| VMware vSphere, vCenter Server, hosts ESXi, Site Recovery Manager (SRM), aplicaciones plugins y bases de datos columna 1 | Consulte https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Herramienta de matriz de interoperabilidad"^] 
|===


=== Requisitos de las herramientas de ONTAP

* Configurar y configurar el entorno de vCenter Server.
* Descargue el archivo .ova.
* Las credenciales de inicio de sesión para la instancia de vCenter Server.
* Elimine la caché del explorador para evitar cualquier problema con la caché del explorador durante la implementación de las herramientas de ONTAP.
* Configure la puerta de enlace predeterminada que utilizará el dispositivo virtual para responder a los ping ICMP.
* Un nombre de host DNS válido para el dispositivo virtual.




=== Requisitos opcionales para SRA

Si está implementando el dispositivo virtual para utilizarlo con VMware Site Recovery Manager, debe tener: * Descargado el `.tar.gz` Archivo para SRA si utiliza el dispositivo SRM.



== Implementar las herramientas de ONTAP

.Pasos
. Descargue `.zip` archivo que contiene binarios y certificados firmados de la https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["Sitio de soporte de NetApp"^] En un sistema vSphere Client para implementar las herramientas de ONTAP.
. Extraiga el `.zip` archive e implemente el `.ova` archivo.
+
Debe implementar el `.ova` Archivo en los sitios de origen y destino si va a implementar SRA.

. Inicie sesión en vSphere Web Client, seleccione *Inicio* > *Host and Clusters*.
. Haga clic con el botón derecho del ratón en el centro de datos necesario y, a continuación, haga clic en *implementar plantilla OVF*.
+
Si utiliza vCenter7.0u3e y versiones posteriores, realice las siguientes acciones; de lo contrario, continúe con el paso 5. Este es un paso opcional para verificar que la integridad binaria de OVA no está alterada.

+
** Descargue el archivo _OTV_INTER_ROOT_CERT_CHAIN.pem_ del sitio de soporte de NetApp.
** Vaya a *vcenter* > *administration* > *certificate management*.
** Haga clic en la opción *Agregar certificado raíz de confianza*.
** Haga clic en *Browse* y proporcione la ruta para el archivo _OTV_INTER_ROOT_CERT_CHAIN.pem_.
** Haga clic en *Agregar*.
+

NOTE: El mensaje Firma de código de confianza - OVCS2 (certificado de confianza) confirma la integridad del archivo OVA descargado. Si ve el mensaje Entrust Code Signing - OVCS2 (certificado no válido), actualice VMware vCenter Server a 7.0U3E o una versión posterior.



. Puede introducir la dirección URL del archivo .ova o buscar la carpeta donde se guarda el archivo .ova y, a continuación, hacer clic en *Siguiente*.
. Especifique los detalles necesarios para completar la implementación.



NOTE: (Opcional) Si desea crear contenedores sin registrar en vCenter Server, seleccione la casilla de comprobación Enable VMware Cloud Foundation (VCF) en la sección Configure vCenter o Enable VCF.

Puede ver el progreso de la implementación desde la ficha *tareas* y esperar a que finalice la implementación.

Como parte de la puesta en marcha, se realizan verificaciones de la suma de comprobación. Si el despliegue falla, haga lo siguiente:

. Verifique vpserver/logs/checksum.log. Si indica que la verificación de la suma de comprobación ha fallado, puede ver la verificación del jar fallido en el mismo registro.
+
El archivo de registro contiene la ejecución de _sha256sum -c /opt/netapp/vpserver/conf/checksums_.

. Verifique vscserver/log/checksum.log. Si indica que la verificación de la suma de comprobación ha fallado, puede ver la verificación del jar fallido en el mismo registro.
+
El archivo de registro contiene la ejecución de _sha256sum -c /opt/netapp/vscerver/etc/checksums_.





=== Puesta en marcha de SRA en SRM

Puede implementar el SRA en un servidor SRM de Windows o en un dispositivo SRM de 8.2.



==== Carga y configuración de SRA en un dispositivo SRM

.Pasos
. Descargue el `.tar.gz` de la https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["Sitio de soporte de NetApp"^].
. En la pantalla del dispositivo SRM, haga clic en *adaptador de replicación de almacenamiento* > *Nuevo adaptador*.
. Cargue el `.tar.gz` Archivo a SRM.
. Vuelva a analizar los adaptadores para verificar que los detalles se actualizan en la página adaptadores de replicación de almacenamiento SRM.
. Inicie sesión con la cuenta de administrador en el dispositivo SRM mediante la función putty.
. Cambie al usuario raíz: `su root`
. En la ubicación del registro, escriba el comando para obtener el identificador del Docker utilizado por el Docker SRA: `docker ps -l`
. Inicie sesión en el ID del contenedor: `docker exec -it -u srm <container id> sh`
. Configure SRM con la dirección IP y contraseña de ONTAP Tools: `perl command.pl -I <otv-IP> administrator <otv-password>`. Es necesario tener una sola cotización en torno al valor de la contraseña.
Se muestra un mensaje indicando que las credenciales de almacenamiento están almacenadas correctamente. El SRA puede comunicarse con el servidor SRA mediante la dirección IP, el puerto y las credenciales proporcionados.




==== Actualizando las credenciales de SRA

.Pasos
. Elimine el contenido del directorio /srm/sra/conf mediante:
+
.. `cd /srm/sra/conf`
.. `rm -rf *`


. Ejecute el comando perl para configurar SRA con las nuevas credenciales:
+
.. `cd /srm/sra/`
.. `perl command.pl -I <otv-IP> administrator <otv-password>`. Es necesario tener una sola cotización en torno al valor de la contraseña.
+
Se muestra un mensaje indicando que las credenciales de almacenamiento están almacenadas correctamente. El SRA puede comunicarse con el servidor SRA mediante la dirección IP, el puerto y las credenciales proporcionados.







==== Habilitar el proveedor VASA y SRA

.Pasos
. Inicie sesión en el cliente web de vSphere mediante la IP de vCenter que se proporcionó durante la puesta en marcha de las herramientas OVA ONTAP.
. En la página de accesos directos, haz clic en *NetApp ONTAP tools* en la sección de complementos.
. En el panel izquierdo de las herramientas de ONTAP, *Configuración > Configuración administrativa > Administrar capacidades*, y habilita las capacidades necesarias.
+

NOTE: El proveedor DE VASA está habilitado de forma predeterminada. Si desea utilizar la funcionalidad de replicación para almacenes de datos vVols, utilice el botón de alternar Enable vVols replication.

. Introduzca la dirección IP de las herramientas de ONTAP para VMware vSphere y la contraseña del administrador y, a continuación, haga clic en *Aplicar*.

