---
permalink: deploy/concept_installation_workflow_for_existing_users_of_ontap_tools.html 
sidebar: sidebar 
keywords:  
summary: Las versiones 9.x de las herramientas de ONTAP para VMware vSphere admiten la actualización sin movimiento a la versión más reciente. 
---
= Flujo de trabajo de implementación para usuarios existentes de herramientas de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las versiones 9.x de las herramientas de ONTAP para VMware vSphere admiten la actualización sin movimiento a la versión más reciente.

Las versiones anteriores de aplicaciones individuales como Virtual Storage Console 6.x, Storage Replication Adapter 2.x, 3.x, 4.x y VASA Provider 6.x utilizan un proceso de actualización diferente. Si tiene estas versiones heredadas de VSC, el proveedor VASA o SRA instaladas en la configuración, póngase en contacto con el soporte técnico para realizar las siguientes operaciones:

. Implemente la última versión de las herramientas de ONTAP.
. Migre los datos de configuración existentes.
+
Los datos de configuración incluyen las credenciales del sistema de almacenamiento, así como las preferencias que se encuentran en `kaminoprefs.xml` y.. `vscPreferences.xml` archivos.



link:../configure/reference_set_ipv4_or_ipv6.html["Utilice el archivo de preferencias para establecer IPv4 o IPv6"]

En muchos casos, es posible que no sea necesario migrar datos de configuración. Sin embargo, si ha personalizado los archivos de preferencias anteriormente, quizás desee revisarlos y realizar cambios similares en las herramientas ONTAP recién implementadas. Puede agregar los sistemas de almacenamiento a las herramientas de ONTAP recién implementadas para VMware vSphere y especificar las credenciales a medida que las añade.

Si va a actualizar desde VASA Provider 6.X, debe cancelar el registro del proveedor VASA antes de la actualización. Consulte la documentación de su versión actual para obtener más detalles.

Si va a actualizar desde SRA 4.0 o una versión anterior:

* Si utiliza SRA 4.0P1, primero debe actualizar a SRA9.6 y, a continuación, realizar una actualización in situ de la versión SRA 9.6. Posteriormente, puede actualizar a la versión más reciente de las herramientas de ONTAP.
+
link:../deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html["Actualice a la versión más reciente de herramientas de ONTAP"]

* Si utiliza SRA 2.1 o 3.0, primero debe tomar nota de los detalles de configuración del sitio existente. Póngase en contacto con el soporte técnico para nuevas implementaciones y migraciones.
+
Los lanzamientos de adaptador de replicación de almacenamiento (SRA) 4,0 para ONTAP también utilizan el proveedor de VASA, por lo que debe cancelar el registro del proveedor de VASA y, a continuación, implementar la versión más reciente de las herramientas de ONTAP. La versión anterior del servidor (`.ova`) se puede quitar cuando la actualización se haya completado.



Si tiene la puesta en marcha del proveedor de VASA, después de la actualización desde la configuración existente, debe configurar el tamaño de memoria para que las herramientas de ONTAP sean de 12 GB con el `Edit Settings` opción. También debe modificar la reserva de memoria virtual. La máquina virtual debe estar apagada para modificar el tamaño de la memoria.

Si tiene la versión 7.2 o 7.2.1 del dispositivo virtual para VSC, proveedor VASA y SRA, no puede realizar la actualización directa a una versión 9.7P1 o posterior del dispositivo unificado. Primero debe actualizar su configuración existente a la versión 9.7 del dispositivo virtual y, a continuación, actualizar a la última versión.

Para actualizar a las herramientas de ONTAP 9,10 y una versión posterior, debe ejecutar el dispositivo virtual 9.7P1 o una versión posterior. No se admite la actualización desde una versión anterior a 9.7P1 del dispositivo virtual.

Si va a implementar la versión más reciente de las herramientas de ONTAP, tendrá que ver el tema link:../deploy/concept_space_and_sizing_requirements_for_ontap_tools_for_vmware_vsphere.html["Requisitos de espacio y ajuste de tamaño para las herramientas de ONTAP"]. El tema link:../deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html["Actualice a la versión más reciente de herramientas de ONTAP"] tiene información sobre cómo realizar una actualización in situ.

*Información relacionada*

https://mysupport.netapp.com/site/tools[]
