---
permalink: deploy/reference_deployment_customization_requirements.html 
sidebar: sidebar 
keywords:  
summary: Debe tener en cuenta algunas limitaciones a la hora de personalizar las herramientas de ONTAP de implementación. 
---
= Consideraciones sobre la personalización de la implantación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe tener en cuenta algunas limitaciones a la hora de personalizar las herramientas de ONTAP de implementación.



== Contraseña de usuario del administrador del dispositivo

No debe usar ningún espacio en la contraseña de administrador.



== Credenciales de la consola de mantenimiento del dispositivo

Debe acceder a la consola de mantenimiento utilizando el nombre de usuario «mant». Puede establecer la contraseña para el usuario «mant» durante la implementación. Puede utilizar el menú Configuración de aplicaciones de la consola de mantenimiento de las herramientas de ONTAP para cambiar la contraseña.



== Credenciales de administrador de vCenter Server

Puede configurar las credenciales de administrador para vCenter Server mientras implementa las herramientas de ONTAP.

Si cambia la contraseña del administrador de vCenter Server, puede actualizar la contraseña del administrador mediante la siguiente URL: \Https://<IP>:8143/Register.html, donde la dirección IP es de las herramientas de ONTAP que se ofrecen durante la implementación.



== Dirección IP de vCenter Server

* Debe proporcionar la dirección IP (IPv4 o IPv6) de la instancia de vCenter Server en la que desea registrar las herramientas de ONTAP.
+
El tipo de herramientas de ONTAP y certificados VASA generados depende de la dirección IP (IPv4 o IPv6) que se proporcionó durante la implementación. Al implementar herramientas de ONTAP, si no ha introducido ningún detalle de IP estático y su DHCP, la red proporciona direcciones IPv4 e IPv6.

* La dirección IP de las herramientas de ONTAP que se utiliza para registrar en vCenter Server depende del tipo de dirección IP de vCenter Server (IPv4 o IPv6) que se introdujo en el asistente de implementación.
+
Tanto las herramientas de ONTAP como los certificados de VASA se generarán con el mismo tipo de dirección IP que se usó durante el registro de vCenter Server.

+

NOTE: : IPv6 solo es compatible con vCenter Server 6.7 y versiones posteriores.





== Propiedades de la red del dispositivo

Si no utiliza DHCP, especifique un nombre de host DNS válido (no cualificado), así como la dirección IP estática de las herramientas ONTAP y los otros parámetros de red. Todos estos parámetros son necesarios para una instalación y funcionamiento correctos.
