---
permalink: deploy/reference_port_requirements_for_vsc.html 
sidebar: sidebar 
keywords: port requirements 
summary: 'De forma predeterminada, Virtual Storage Console \(VSC\) utiliza puertos designados para habilitar la comunicación entre sus componentes, que incluyen sistemas de almacenamiento y VMware vCenter Server. Si tiene firewalls habilitados, debe asegurarse de que los firewalls están configurados para permitir excepciones.' 
---
= Requisitos de puertos para VSC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
De forma predeterminada, Virtual Storage Console (VSC) utiliza puertos designados para habilitar la comunicación entre sus componentes, incluidos los sistemas de almacenamiento y VMware vCenter Server. Si tiene firewalls habilitados, debe asegurarse de que los firewalls están configurados para permitir excepciones.

Para firewalls diferentes de Windows, debe otorgar acceso manualmente a puertos específicos que utiliza VSC. Si no concede acceso a estos puertos, aparecerá un mensaje de error como el siguiente.

`Unable to communicate with the server.`

VSC utiliza los siguientes puertos TCP bidireccionales predeterminados:

|===


| *Número de puerto predeterminado* | *Descripción* 


 a| 
9083
 a| 
Cuando se encuentra habilitada, tanto el proveedor VASA como el adaptador de replicación de almacenamiento (SRA) utilizan este puerto para comunicarse con vCenter Server. Este puerto también es necesario para obtener los ajustes de TCP/IP. Este puerto se utiliza para descargar el paquete de soporte VP, acceder a la interfaz de usuario Web-CLI y la comunicación de la ruta de control de VMware a VP.



 a| 
443
 a| 
Según la forma en que haya configurado sus credenciales, VMware vCenter Server y los sistemas de almacenamiento escuchan las comunicaciones seguras en este puerto. El puerto se utiliza en la arquitectura de comunicación cliente-servidor. El puerto 443 está habilitado de manera predeterminada para conexiones seguras. El cliente, que puede ser cualquier cliente de automatización que utilice la API de REST, inicia la conexión con el servidor y los puntos finales intercambian datos.



 a| 
8143
 a| 
VSC escucha comunicaciones seguras en este puerto. El puerto se utiliza en la arquitectura de comunicación cliente-servidor. El cliente, que puede ser cualquier cliente de automatización que utilice la API de REST, inicia la conexión con el servidor y los puntos finales intercambian datos. Este puerto está habilitado para los servicios VSC y para exportar registros del servidor VSC. La página register.html está alojada en este puerto. El Swagger DE REST queda expuesto en este puerto.

|===

NOTE: Debe haber habilitado el protocolo de mensajes de control de Internet (ICMP) antes de implementar las herramientas de ONTAP.

Si ICMP está deshabilitado, genera errores en la configuración inicial de las herramientas de ONTAP y VSC no puede iniciar los servicios de VSC y VASA Provider después de la implementación. Es necesario habilitar manualmente los servicios de VSC y proveedor VASA después de la implementación.
