---
permalink: deploy/reference_port_requirements_for_vsc.html 
sidebar: sidebar 
keywords: port requirements 
summary: De forma predeterminada, las herramientas de ONTAP utilizan puertos designados para permitir la comunicación entre sus componentes, que incluyen sistemas de almacenamiento y VMware vCenter Server. Si tiene firewalls habilitados, debe asegurarse de que los firewalls están configurados para permitir excepciones. 
---
= Requisitos de puertos para las herramientas de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
De forma predeterminada, las herramientas de ONTAP utilizan puertos designados para permitir la comunicación entre sus componentes, que incluyen sistemas de almacenamiento y VMware vCenter Server. Si tiene firewalls habilitados, debe asegurarse de que los firewalls están configurados para permitir excepciones.

En el caso de firewalls que no sean Windows, debe conceder manualmente acceso a puertos específicos que utilizan las herramientas de ONTAP. Si no concede acceso a estos puertos, aparecerá un mensaje de error como el siguiente.

`Unable to communicate with the server.`

Las herramientas de ONTAP utilizan los siguientes puertos TCP bidireccionales predeterminados:

|===


| *Número de puerto predeterminado* | *Descripción* 


 a| 
9083
 a| 
Cuando se encuentra habilitada, tanto el proveedor VASA como el adaptador de replicación de almacenamiento (SRA) utilizan este puerto para comunicarse con vCenter Server. Este puerto también es necesario para obtener los ajustes de TCP/IP. Este puerto se utiliza para descargar el paquete de soporte VP, acceder a la interfaz de usuario Web-CLI y la comunicación de la ruta de control de VMware a VP.



 a| 
443
 a| 
Según la forma en que haya configurado sus credenciales, VMware vCenter Server y los sistemas de almacenamiento escuchan las comunicaciones seguras en este puerto. El puerto se utiliza en la arquitectura de comunicación cliente-servidor. El puerto 443 está habilitado de manera predeterminada para conexiones seguras. El cliente, que puede ser cualquier cliente de automatización que utilice la API de REST, inicia la conexión con el servidor y los puntos finales intercambian datos.



 a| 
8143
 a| 
Las herramientas de ONTAP escuchan las comunicaciones seguras en este puerto. El puerto se utiliza en la arquitectura de comunicación cliente-servidor. El cliente, que puede ser cualquier cliente de automatización que utilice la API de REST, inicia la conexión con el servidor y los puntos finales intercambian datos. Este puerto está habilitado para los servicios de herramientas de ONTAP y para exportar los registros del servidor de herramientas de ONTAP. La página register.html está alojada en este puerto. El Swagger DE REST queda expuesto en este puerto.

|===

NOTE: Debe haber habilitado el protocolo de mensajes de control de Internet (ICMP) antes de implementar las herramientas de ONTAP.

Si ICMP está deshabilitado, la configuración inicial de herramientas ONTAP genera errores y las herramientas de ONTAP no pueden iniciar las herramientas ONTAP y los servicios del proveedor VASA después de la implementación. Debe habilitar manualmente las herramientas ONTAP y los servicios del proveedor VASA después de la implementación.
