---
permalink: deploy/reference_considerations_for_deploying_virtual_appliance_for_vsc_vasa_provider_and_sra.html 
sidebar: sidebar 
keywords: Virtual Storage Console,Storage Replication Adapter 
summary: Antes de implementar las herramientas de ONTAP para VMware vSphere, es recomendable planificar la implementación y decidir cómo se configurarán las herramientas de ONTAP en su entorno. 
---
= Consideraciones que tener en cuenta para implementar las herramientas de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de implementar las herramientas de ONTAP para VMware vSphere, es recomendable planificar la implementación y decidir cómo se configurarán las herramientas de ONTAP en su entorno.

La siguiente tabla presenta una descripción general de lo que debe tener en cuenta antes de implementar herramientas de ONTAP.

|===


| *Consideraciones* | *Descripción* 


 a| 
Puesta en marcha por primera vez de herramientas de ONTAP
 a| 
La puesta en marcha de las herramientas de ONTAP instala automáticamente las características de las herramientas de ONTAP.

link:../deploy/concept_installation_workflow_for_new_users.html["Flujo de trabajo de implementación para nuevos usuarios de herramientas de ONTAP para VMware vSphere"]



 a| 
Actualizar desde una puesta en marcha existente de herramientas de ONTAP
 a| 
El procedimiento de actualización de una implementación existente de herramientas de ONTAP en herramientas de ONTAP depende de la versión de las herramientas de ONTAP y de si ha implementado las herramientas de ONTAP. La sección de flujos de trabajo de implementación y actualización contiene más información.

link:concept_installation_workflow_for_existing_users_of_vsc.html["Flujo de trabajo de implementación para usuarios existentes de herramientas de ONTAP"]

Prácticas recomendadas antes de una actualización:

* Debe registrar información sobre los sistemas de almacenamiento que se están usando y sus credenciales.
+
Después de la actualización, debe verificar que todos los sistemas de almacenamiento se detectaron automáticamente y que tienen las credenciales correctas.

* Si ha modificado cualquiera de los roles estándar de herramientas de ONTAP, debe copiar esos roles para guardar los cambios.
+
Las herramientas de ONTAP sobrescriben las funciones estándar con los valores predeterminados actuales cada vez que reinicia el servicio de herramientas de ONTAP.





 a| 
Regeneración de un certificado SSL para las herramientas ONTAP
 a| 
El certificado SSL se genera automáticamente al implementar las herramientas de ONTAP. Es posible que tenga que regenerar el certificado SSL para crear un certificado específico de sitio.

link:../configure/task_regenerate_an_ssl_certificate_for_vsc.html["Regenere un certificado SSL para Virtual Storage Console"]



 a| 
Configuración de los valores del servidor ESXi
 a| 
Aunque la mayoría de los valores del servidor ESXi se establecen de forma predeterminada, es una buena práctica comprobar los valores. Estos valores se basan en pruebas internas. En función de su entorno, es posible que deba cambiar algunos de los valores para mejorar el rendimiento.

* link:../configure/task_configure_esx_server_multipathing_and_timeout_settings.html["Configure los valores de multivía y de tiempo de espera del servidor ESXi"]
* link:../configure/reference_esxi_host_values_set_by_vsc_for_vmware_vsphere.html["Los valores de host de ESXi se establecen mediante las herramientas de ONTAP para VMware vSphere"]




 a| 
Valores de tiempo de espera del sistema operativo invitado
 a| 
Los scripts de tiempo de espera del sistema operativo invitado (SO invitado) configuran los valores de tiempo de espera de I/o SCSI para sistemas operativos invitados de Linux, Solaris y Windows compatibles con el fin de proporcionar una conducta de conmutación por error correcta.

|===
En la siguiente tabla se muestra una descripción general de lo que se necesita para configurar las herramientas de ONTAP.

|===


| *Consideraciones* | *Descripción* 


 a| 
Requisitos de control de acceso basado en roles (RBAC)
 a| 
Las herramientas de ONTAP son compatibles con el control de acceso basado en roles de vCenter Server y de ONTAP. La cuenta utilizada para registrar herramientas de ONTAP en vCenter Server (`\https://<appliance_ip>:8143/Register.html`) Debe ser un administrador de vCenter Server (asignado al rol de administrador de vCenter Server o de administrador). Si planea ejecutar herramientas de ONTAP como administrador, debe tener todos los permisos y privilegios necesarios para todas las tareas.

Si su empresa requiere restringir el acceso a objetos de vSphere, puede crear y asignar roles de herramientas estándar de ONTAP a los usuarios para cumplir los requisitos de vCenter Server.

Puede crear los roles de ONTAP recomendados mediante System Manager de ONTAP mediante el archivo JSON proporcionado con las herramientas de ONTAP.

Si un usuario intenta realizar una tarea sin los privilegios y permisos correctos, las opciones de la tarea aparecen atenuadas.

* link:../concepts/concept_standard_roles_packaged_with_virtual_appliance_for_vsc_vp_and_sra.html["Funciones estándar incluidas en las herramientas de ONTAP"]
* link:../concepts/concept_ontap_role_based_access_control_feature_for_ontap_tools.html["Permisos para los sistemas de almacenamiento ONTAP y objetos de vSphere"]




 a| 
Versión de ONTAP
 a| 
Sus sistemas de almacenamiento deben ejecutar ONTAP 9,7, 9.8P1 o posterior.



 a| 
Perfiles de funcionalidad de almacenamiento
 a| 
Para usar perfiles de funcionalidad de almacenamiento o configurar alarmas, es necesario habilitar VASA Provider para ONTAP. Después de habilitar VASA Provider, es posible configurar almacenes de datos de VMware Virtual Volumes (vVols), y se pueden crear y gestionar perfiles de capacidades de almacenamiento y alarmas. Las alarmas se avisan cuando un volumen o un agregado tienen una capacidad casi completa o cuando un almacén de datos ya no cumple con el perfil de la funcionalidad de almacenamiento asociada.

|===