---
permalink: deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords: Virtual Storage Console, Storage Replication Adapter 
summary: Puede realizar una actualización in situ a la versión más reciente de herramientas de ONTAP desde la configuración 9,10 existente o posterior siguiendo las instrucciones que se proporcionan aquí. 
---
= Actualice a la versión más reciente de herramientas de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede realizar una actualización in situ a la versión más reciente de herramientas de ONTAP desde la versión 9,10 existente o una versión posterior siguiendo las instrucciones que se proporcionan aquí.

*Lo que necesitará*

* Debe haber descargado el archivo _.iso_ para la última versión de las herramientas de ONTAP.
* Debe haber reservado al menos 12 GB de RAM para que las herramientas de ONTAP funcionen de forma óptima después de la actualización.
* Debe limpiar la caché del explorador de vSphere Client.
+
link:../deploy/task_clean_the_vsphere_cached_downloaded_plug_in_packages.html["Borre los paquetes de plugins descargados en caché de vSphere"]



Realice los siguientes pasos para validar el archivo _.iso_ si es necesario. Este es un paso opcional:

. Extraiga la clave pública del certificado de firma de código emitido de Entrust (OTV_ISO_CERT.pem) openssl x509 -in otv_iso_CERT.pem -pubkey -noout > csc-prod-otv-sra-tgz.pub
. Verifique la firma en el resumen utilizando la clave pública (este paso debe suceder en el sistema de usuario final antes de instalar el binario. El paquete de certificados debe incluirse en el paquete de implementación)
+
openssl dgst -sha256 -Verify csc-prod-otv-sra-TGZ.pub -signature netapp-ontap-tools-for-vmware-vsphere-9,12-9327-upgrade-iso.sig netapp-ontap-tools-for-vmware-vsphere-9.12-9327-upgrade.iso



El estado del proveedor de VASA de la implementación existente se conserva después de la actualización. Después de la actualización, es necesario habilitar o deshabilitar manualmente VASA Provider según sus requisitos. Sin embargo, es mejor habilitar VASA Provider incluso si los volúmenes virtuales de VMware (vVols) no están en uso, ya que permite los perfiles de funcionalidades de almacenamiento para el aprovisionamiento de almacenes de datos tradicionales y las alarmas de almacenamiento.


NOTE: Puede realizar una actualización in situ a la versión más reciente de herramientas de ONTAP solo a partir de la versión 9,10 o posterior existente.


NOTE: Desde las herramientas de ONTAP 9,12, actualizar todos los sistemas de almacenamiento La autenticación y el proceso de comunicación ha cambiado de la autenticación básica a la autenticación basada en certificados gracias a la confianza automática en los certificados de almacenamiento de ONTAP. No es necesario realizar ninguna acción por parte del usuario.

Se restringe la adición de un sistema de almacenamiento sin autenticación de certificados.

Si el sistema de almacenamiento se añade con un usuario de ámbito de clúster creado personalizado mediante el archivo json y desea actualizar a la versión 9,12 y versiones posteriores, entonces
Ejecute los comandos siguientes en la interfaz de línea de comandos de ONTAP antes de actualizar para habilitar la comunicación basada en certificado entre las herramientas de ONTAP para VMware vSphere y ONTAP.

. _security login role create -role <existing-role-name> -cmddirname «security login show» -access all_
. _security login role create -role <existing-role-name> -cmddirname «security certificate show» -access all_
. _security login role create -role <existing-role-name> -cmddirname «security certificate install» -access all_


Si el sistema de almacenamiento se añade con un usuario de ámbito de SVM creado personalizado mediante el archivo json y desea actualizar a la versión 9,12 y versiones posteriores, después, ejecute los siguientes comandos en la interfaz de línea de comandos de ONTAP con acceso de administrador del clúster antes de la actualización para habilitar la comunicación basada en certificados entre las herramientas de ONTAP para VMware vSphere y ONTAP:

. _security login role create -role <existing-role-name> -cmddirname «security certificate install» -access all -vserver <vserver-name>_
. _security login role create -role <existing-role-name> -cmddirname «security certificate show» -access all -vserver <vserver-name>_
. _security login create -user-or-group-name <user> -application http -authentication-method cert -role <existing-role-name> -vserver <vserver-name>_
. _security login create -user-or-group-name <user> -application ontapi -authentication-method cert -role <existing-role-name> -vserver <vserver-name>_


* Pasos*

. Monte el archivo _.iso_ descargado en las herramientas de ONTAP:
+
.. Haga clic en *Editar configuración* > *Unidad de DVD/CD-ROM*.
.. Seleccione *Datastore ISO* file en la lista desplegable.
.. Desplácese hasta el archivo _.iso_ descargado y, a continuación, seleccione la casilla de verificación *conectar al encender*.


. Acceda a la pestaña Resumen de las herramientas de ONTAP implementadas.
. Inicie la consola de mantenimiento.
. En el indicador «Menú principal», introduzca la opción `2` Para *Configuración del sistema* y, a continuación, introduzca la opción `8` Para *actualización*.
+
Cuando se complete la actualización, se reinicien las herramientas ONTAP. Las herramientas de ONTAP se registran en vCenter Server con la misma dirección IP que antes de la actualización.

. Si desea que se registren herramientas de ONTAP en la instancia de vCenter Server con la dirección IPv6, debe realizar lo siguiente:
+
.. Cancele el registro de las herramientas de ONTAP.
.. Registre la dirección IPv6 de las herramientas de ONTAP en vCenter Server mediante la página *Register*.
.. Vuelva a generar las herramientas de ONTAP para los certificados de VMware vSphere y VASA Provider después del registro.


+

IMPORTANT: IPv6 solo es compatible con vCenter Server 6.7 y versiones posteriores.

. Cierre sesión y vuelva a iniciar sesión en vSphere Client para ver las herramientas ONTAP implementadas.
+
.. Cierre la sesión en vSphere Web Client o vSphere Client existente y cierre la ventana.
.. Inicie sesión en vSphere Client.
+
Es posible que el plugin se actualice en vSphere Client durante unos minutos.





[NOTE]
====
* A partir de las herramientas de ONTAP para VMware vSphere 9,12, la autenticación con ONTAP se realiza mediante un certificado. Es posible añadir un certificado firmado por una CA o un certificado autofirmado. Consulte, link:../configure/task_modify_storage_system.html["Modificar los sistemas de almacenamiento"] si desea obtener instrucciones.
* Si se actualiza desde la versión 7.0 de las herramientas de ONTAP a la versión más reciente de las herramientas de ONTAP, primero es necesario crear perfiles de funcionalidad de almacenamiento antes de intentar editar una política de almacenamiento de máquina virtual existente, o bien es posible que aparezca un error con valores incorrectos o faltantes.
* Si actualiza desde una versión anterior a la versión más reciente de las herramientas de ONTAP, se observe que `vvol.rebalance.threshold` falta la propiedad en el archivo "vvol.properties".
+
El valor predeterminado de la propiedad se establece en 85%.* Después de actualizar a la última versión de herramientas de ONTAP que tiene habilitado FIPS, pero tiene una versión anterior de vCenter en la que no se admite FIPS, la implementación seguirá funcionando.
Pero si actualiza vCenter a la versión más reciente compatible con FIPS y tiene una versión anterior de herramientas de ONTAP, la implementación solo funcionará si FIPS está deshabilitado en vCenter.



====