---
permalink: deploy/task_upgrade_storage_replication_adapter.html 
sidebar: sidebar 
keywords: SRA, upgrade 
summary: 'Después de actualizar las herramientas de ONTAP o implementar la versión más reciente de las herramientas de ONTAP, debe actualizar el adaptador de replicación de almacenamiento \(SRA\).' 
---
= Actualice el adaptador de replicación de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de actualizar las herramientas de ONTAP o implementar la versión más reciente de las herramientas de ONTAP, debe actualizar el adaptador de replicación de almacenamiento (SRA).

*Paso*

. Debe actualizar al adaptador más reciente mediante uno de los siguientes procedimientos basados en su adaptador:
+
|===


| *Para...* | *Realice lo siguiente...* 


 a| 
Windows
 a| 
.. Inicie sesión en SRM Windows Server.
.. Cambie la ruta del sistema a. `C:\Program Files\VMware\VMware vCenter Site Recovery Manager\external\perl\c\bin`
.. Introduzca la dirección IP y la contraseña de las herramientas implementadas de ONTAP .




 a| 
Adaptador basado en dispositivo
 a| 
.. Inicie sesión en la página Administración de dispositivos SRM.
.. Haga clic en *adaptador de replicación de almacenamiento* y haga clic en *Eliminar* para eliminar el SRA existente.
.. Haga clic en *Nuevo adaptador* > *examinar*.
.. Haga clic aquí para seleccionar el último archivo de tarball de SRA que descargó del sitio de soporte de NetApp y, a continuación, haga clic en *instalar*.
.. Configure SRA en el dispositivo SRM.
+
link:../protect/task_configure_sra_on_srm_appliance.html["Configuración de SRA en el dispositivo SRM"]



|===

