---
permalink: deploy/task_deploy_ontap_tools.html 
sidebar: sidebar 
keywords:  
summary: Para utilizar las herramientas ONTAP para el dispositivo VMware vSphere, ponga en marcha las herramientas de ONTAP para VMware vSphere en el entorno y especifique los parámetros necesarios. 
---
= Cómo implementar las herramientas de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para utilizar las herramientas ONTAP para el dispositivo VMware vSphere, ponga en marcha las herramientas de ONTAP para VMware vSphere en el entorno y especifique los parámetros necesarios.

*Lo que necesitará*

* Debe tener la versión compatible de vCenter Server.
+

NOTE: Es posible registrar las herramientas de ONTAP para VMware vSphere en una implementación de Windows de vCenter Server o en una implementación de VMware vCenter Server Virtual Appliance (vcsa).

+
https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Herramienta de matriz de interoperabilidad"^]

* Debe haber configurado y configurado el entorno de vCenter Server.
* Debe haber configurado un host ESXi para la máquina virtual.
* Debe haber descargado el archivo _.ova_.
* Debe tener credenciales de inicio de sesión de administrador para la instancia de vCenter Server.
* Debe haber cerrado sesión y cerrado todas las sesiones del explorador de vSphere Client y haber eliminado la caché del explorador para evitar cualquier problema con la caché del explorador durante la implementación de las herramientas de ONTAP.
* Debe haber habilitado el protocolo de mensajes de control de Internet (ICMP).
+
Si ICMP está deshabilitado, se produce un error en la configuración inicial de las herramientas de ONTAP para VMware vSphere. Debe habilitar manualmente las herramientas de ONTAP para los servicios de proveedor VASA y VMware vSphere después de la implementación.



*Acerca de esta tarea*

El proveedor VASA está habilitado de forma predeterminada para una instalación nueva de las herramientas de ONTAP para VMware vSphere. Pero, en caso de una actualización desde una versión anterior, se conserva el estado de VASA Provider y es posible que deba habilitar el proveedor de VASA de forma manual.

link:../deploy/task_enable_vasa_provider_for_configuring_virtual_datastores.html["Habilite VASA Provider para configurar almacenes de datos virtuales"]

* Pasos*

. Inicie sesión en vSphere Client.
. Selecciona *Inicio* > *Hosts and Clusters*.
. Haga clic con el botón derecho en el centro de datos requerido y luego haga clic en *Desplegar plantilla OVF...*.
+

NOTE: No implemente herramientas de ONTAP para máquinas virtuales VMware vSphere en un almacén de datos vVols que gestiona.

. Seleccione el método correspondiente para proporcionar el archivo de implementación para las herramientas de ONTAP y, a continuación, haga clic en *Siguiente*.
+
|===


| *Ubicación* | *Acción* 


 a| 
URL
 a| 
Proporcione la URL del archivo _.ova_ para las herramientas de ONTAP.



 a| 
Carpeta
 a| 
Extraiga el archivo .zip, que contiene el archivo .ova en el sistema local. En la página Seleccionar una plantilla OVF, especifique la ubicación del archivo .ova dentro de la carpeta extraída.

|===
. Introduzca los detalles para personalizar el asistente de implementación.
+
(Opcional) en la sección Configure vCenter o Enable VCF, seleccione la casilla de comprobación *Enable VMware Cloud Foundation (VCF)* y proporcione una contraseña para las credenciales de las herramientas de ONTAP. Las herramientas de ONTAP almacenan los detalles del usuario en un formato codificado. Para cualquier comunicación desde las herramientas de ONTAP con vCenter, se utilizan estos detalles de usuario de vCenter.
No es necesario proporcionar una dirección IP, pero es obligatorio proporcionar una contraseña.
Consulte lo siguiente para obtener toda la información.

+
** link:../deploy/reference_considerations_for_deploying_ontap_tools_for_vmware_vsphere.html["Consideraciones sobre la personalización de la implantación"]
** link:../deploy/vmware_cloud_foundation_mode_deployment.html["VMware Cloud Foundation modo de puesta en marcha para herramientas de ONTAP"]


. Revise los datos de configuración y, a continuación, haga clic en *Siguiente* para finalizar la implementación.
+
Mientras espera a que termine la implementación, puede ver el progreso de la implementación en la pestaña tareas.

. Encienda la máquina virtual de herramientas de ONTAP y, a continuación, abra una consola de la máquina virtual que ejecuta las herramientas de ONTAP.
. Compruebe que las herramientas de ONTAP se están ejecutando una vez completada la implementación.
. Si las herramientas de ONTAP no están registradas en ninguna instancia de vCenter Server, utilice `\https://appliance_ip:8143/Register.html` Para registrar la instancia de herramientas de ONTAP. Register.html le redirige a la página de Swagger. A partir de las herramientas de ONTAP 9,12, el registro de las herramientas de ONTAP con vCenter se produce desde la página de Swagger.
+
Use la API POSTERIOR para registrar herramientas de ONTAP en vCenter a partir de la versión 9,12.

+
[listing]
----
/2.0/plugin/vcenter
----
. Cierre sesión y vuelva a iniciar sesión en vSphere Client para ver las herramientas ONTAP implementadas.
+
Es posible que el plugin se actualice en vSphere Client durante unos minutos.

+
*Solución de problemas:* Si no puede ver el plugin incluso después de iniciar sesión, debe limpiar la caché de vSphere Client.

+
link:../deploy/task_clean_the_vsphere_cached_downloaded_plug_in_packages.html["Borre los paquetes de plugins descargados en caché de vSphere"]



link:../deploy/task_enable_vasa_provider_for_configuring_virtual_datastores.html["Habilite VASA Provider para configurar almacenes de datos virtuales"]

*Información relacionada*

https://kb.netapp.com/?title=Advice_and_Troubleshooting%2FData_Storage_Software%2FVirtual_Storage_Console_for_VMware_vSphere%2FError_during_fresh_deployment_of_virtual_appliance_for_VSC%252C_VASA_Provider%252C_and_SRA["Error al poner en marcha nuevos dispositivos virtuales para VSC, proveedores VASA y SRA"]
