---
permalink: deploy/task_enable_vasa_provider_for_configuring_virtual_datastores.html 
sidebar: sidebar 
keywords:  
summary: 'Las herramientas de ONTAP para VMware vSphere tienen habilitada la funcionalidad de proveedor de VASA de forma predeterminada. Puede configurar almacenes de datos VMware Virtual Volumes \(vVols\) con los perfiles de capacidad de almacenamiento necesarios para cada almacén de datos vVols.' 
---
= Habilite VASA Provider para configurar almacenes de datos virtuales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las herramientas de ONTAP para VMware vSphere tienen habilitada la funcionalidad de proveedor de VASA de forma predeterminada. Puede configurar almacenes de datos VMware Virtual Volumes (vVols) con perfiles de capacidad de almacenamiento necesarios para cada almacén de datos vVols.

*Lo que necesitará*

* Debe haber configurado la instancia de vCenter Server y ESXi.
* Debe haber implementado las herramientas de ONTAP .


*Acerca de esta tarea*

Si la funcionalidad del proveedor VASA está deshabilitada antes de actualizar a la versión 9.7.1 de las herramientas de ONTAP , la funcionalidad del proveedor VASA permanece deshabilitada después de la actualización. Esta versión le permite habilitar la función de replicación vVols para almacenes de datos vVols.

* Pasos*

. Inicie sesión en la interfaz de usuario web de VMware vSphere.
. En vSphere Client, haga clic en *Menú* > *NetApp ONTAP tools* Consola.
. Haga clic en *Configuración*.
. Haga clic en *Administrar capacidades* en la ficha Configuración administrativa.
. En el cuadro de diálogo gestionar funcionalidades, seleccione la extensión VASA Provider para habilitar.
. Si desea utilizar la capacidad de replicación para almacenes de datos vVols, utilice el botón de alternar *Activar replicación vVols*.
. Introduzca la dirección IP de las herramientas de ONTAP y la contraseña del administrador y, a continuación, haga clic en *aplicar*.
+

NOTE: Si el estado del proveedor VASA se muestra como "'fuera de línea'" incluso después de habilitar la extensión del proveedor VASA, compruebe la ``/var/log/vmware/vmware-sps/sps.log` Archivar los errores de conexión con VASA Provider o reiniciar el servicio "'vmware-sps'".



*Información relacionada*

https://mysupport.netapp.com/site/global/dashboard["Soporte de NetApp"]
