---
permalink: deploy/task_install_the_nfs_vaai_plug_in.html 
sidebar: sidebar 
keywords:  
summary: 'Es posible instalar el plugin de NetApp NFS para VMware vStorage APIs for Array Integration \(VAAI\) mediante la interfaz gráfica de usuario de herramientas de ONTAP para VMware vSphere.' 
---
= Instale el complemento NFS VAAI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se puede instalar el plugin de NetApp NFS para VMware vStorage APIs for Array Integration (VAAI) mediante la interfaz gráfica de usuario de las herramientas de ONTAP para VMware vSphere.

*Lo que necesitará*

* Debe haber descargado el paquete de instalación del plugin de NFS para VAAI (``.vib`) Desde el sitio de soporte de NetApp. https://mysupport.netapp.com/site/global/dashboard["Soporte de NetApp"]
* Debe haber instalado el host ESXi 6.5 o posterior y ONTAP 9.1 o posterior.
* Debe haber encendido el host ESXi y montado un almacén de datos NFS.
* Debe haber establecido los valores de `DataMover.HardwareAcceleratedMove`, `DataMover.HardwareAcceleratedInit`, y. `VMFS3.HardwareAcceleratedLocking` ajustes del host a «'1'».
+
Estos valores se establecen automáticamente en el host ESXi cuando se actualiza el cuadro de diálogo Recomendar Settings.

* Debe haber habilitado la opción vstorage en la máquina virtual de almacenamiento (SVM) mediante el `vserver nfs modify -vserver vserver_name -vstorage enabled` comando.
* Debe tener ESXi 7.0 Update 1 o posterior si utiliza el plugin VAAI para NFS de NetApp 2.0.
* Debe tener las versiones de vSphere 7.x, ya que vSphere 6,5 quedó obsoleto y vSphere 8.x no es compatible.


* Pasos*

. Cambie el nombre de `.vib` Archivo que ha descargado del sitio de soporte de NetApp en NetAppNasPlugin.vib para que coincida con el nombre predefinido que utiliza las herramientas de ONTAP.
. Haga clic en *Configuración* en la página de inicio de ONTAP Tools.
. Haga clic en la ficha *NFS VAAI Tools*.
. Haga clic en *Cambiar* en la sección *Versión existente*.
. Examine y seleccione el nombre cambiado `.vib` File y, a continuación, haga clic en *Upload* para cargar el archivo en las herramientas de ONTAP.
. En la sección Install on ESXi hosts, seleccione el host ESXi en el que desea instalar el plugin NFS VAAI y, a continuación, haga clic en *Install*.
+
Debe seguir las instrucciones que aparecen en pantalla para completar la instalación. Puede supervisar el progreso de la instalación en la sección Tasks de vSphere Web Client.

. Reinicie el host ESXi después de que finalice la instalación.
+
Cuando reinicia el host ESXi, las herramientas ONTAP detectan automáticamente el plugin VAAI de NFS. No es necesario realizar pasos adicionales para habilitar el plugin.


