---
permalink: deploy/task_clean_the_vsphere_cached_downloaded_plug_in_packages.html 
sidebar: sidebar 
keywords: clean up browser cache 
summary: Si los plugins no se actualizan automáticamente después de implementar o actualizar herramientas de ONTAP, debe limpiar los paquetes de plugins de descarga almacenados en caché en el explorador y en el servidor vCenter para resolver problemas de plugins de vCenter Server. 
---
= Borre los paquetes de plugins descargados en caché de vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/
:firstname: [.lead]
:author: [.lead]
:authorinitials: [
:authors: [.lead]
:revnumber: 
:revdate: you should clean up the cached download plug-in packages on the browser and on the vCenter Server to resolve vCenter Server plug-in issues.


* Pasos*

. Cierre sesión en el cliente web de vSphere o la interfaz de usuario de vSphere existente.
. Quite la caché del explorador.
. Quite los paquetes de plugins almacenados en caché de vSphere Client. Para VCSA, realice lo siguiente:
+
.. SSH en el dispositivo VCSA.
.. Detenga el servicio VMware vSphere Client:
`service-control --stop vsphere-ui`
.. Cambie los directorios al directorio de extensiones de la interfaz de usuario del cliente de vCenter: `cd /etc/vmware/vsphere-ui/vc-packages/vsphere-client-serenity`
.. Quite los paquetes de plugins almacenados en caché específicos de NetApp mediante el `rm -rf` comandos:
+
`rm -rf com.netapp.nvpf.webclient-*`

+
`rm -rf com.netapp.vasa.vvol.webclient-*`

+
`rm -rf com.netapp.vsch5-*`

.. Inicie el servicio VMware vSphere Client:
`service-control --start vsphere-ui`



