---
permalink: protect/concept_migration_of_disaster_recovery_setup_from_windows_to_appliance.html 
sidebar: sidebar 
keywords: Migration 
summary: 'Si utiliza el Administrador de recuperación de sitios \(SRM\) basado en Windows para la recuperación ante desastres y desea utilizar SRM Appliance para la misma configuración, debe migrar la configuración de recuperación ante desastres de Windows al SRM basado en dispositivos.' 
---
= Migración de SRM de Windows a SRM Appliance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si utiliza Site Recovery Manager (SRM) basado en Windows para la recuperación ante desastres y desea utilizar SRM para la misma configuración, debe migrar su configuración de recuperación ante desastres de Windows a SRM basado en dispositivos.

Los pasos involucrados en la migración de la recuperación ante desastres son:

. Actualice sus herramientas de ONTAP actuales para el dispositivo de VMware vSphere a la versión más reciente.
+
link:../deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html["Actualice a la versión más reciente de herramientas de ONTAP"]

. Migración de un adaptador de replicación de almacenamiento basado en Windows al SRA basado en dispositivos.
. Migración de datos de Windows SRM a SRM Appliance.


Consulte https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/site-recovery-manager/8-8/site-recovery-manager-installation-and-configuration-8-8.html["Instalación y configuración de Site Recovery Manager"] para obtener información detallada sobre los pasos
