---
permalink: protect/task_pair_protected_and_recovery_sites.html 
sidebar: sidebar 
keywords:  
summary: 'Debe emparejar los sitios protegidos y de recuperación creados mediante vSphere Client para habilitar el adaptador de replicación de almacenamiento \(SRA\) para detectar los sistemas de almacenamiento.' 
---
= Sitios protegidos para pares y de recuperación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe emparejar los sitios protegidos y de recuperación creados mediante vSphere Client para habilitar el adaptador de replicación de almacenamiento (SRA) para detectar los sistemas de almacenamiento.

*Lo que necesitará*

* Debe haber instalado Site Recovery Manager (SRM) en los sitios protegidos y de recuperación.
* Debe haber instalado SRA en los sitios protegidos y de recuperación.


*Acerca de esta tarea*

Las configuraciones de dispersión de SnapMirror son las que permiten replicar un volumen de origen en dos destinos diferentes. Esto crea un problema durante la recuperación cuando el SRM necesita recuperar la máquina virtual del destino. * Pasos*

. Haga doble clic en *Site Recovery* en la página de inicio de vSphere Client y, a continuación, haga clic en *Sitios*.
. Haga clic en *objetos* > *acciones* > *Vincular sitios*.
. En el cuadro de diálogo Pair Site Recovery Manager Servers, introduzca la dirección del controlador de servicios de plataforma del sitio protegido y, a continuación, haga clic en *Siguiente*.
. En la sección Select vCenter Server, realice lo siguiente:
+
.. Compruebe que vCenter Server del sitio protegido aparece como candidato coincidente al emparejar.
.. Introduzca las credenciales administrativas de SSO y, a continuación, haga clic en *Finalizar*.


. Si se le solicita, haga clic en *Sí* para aceptar los certificados de seguridad.


*resultado*

Tanto los sitios protegidos como los de recuperación aparecerán en el cuadro de diálogo objetos.
