---
permalink: protect/task_update_sra_credentials.html 
sidebar: sidebar 
keywords: SRA credentials, updating 
summary: Para que el SRM se comunique con el SRA, debe actualizar las credenciales del SRA en el servidor SRM si ha modificado las credenciales. 
---
= Actualice las credenciales del SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para que el SRM se comunique con el SRA, debe actualizar las credenciales del SRA en el servidor SRM si ha modificado las credenciales.

Debe eliminar la contraseña de nombre de usuario de las herramientas de ONTAP almacenadas en caché de la carpeta de la máquina SRM y volver a instalar el SRA.

*Lo que necesitará*

Debe haber ejecutado los pasos mencionados en el tema link:../protect/task_configure_sra_on_srm_appliance.html["Configuración de SRA en el dispositivo SRM"]

* Pasos*

. Ejecute los siguientes comandos para eliminar la carpeta de máquina SRM almacenada en caché ONTAP tools contraseña de nombre de usuario:
+
.. `sudo su <enter root password>`
.. `docker ps`
.. `docker exec -it <container_id> sh`
.. `cd /conf`
.. `rm -rf *`


. Ejecute el comando perl para configurar SRA con las nuevas credenciales:
+
.. `cd ..`
.. `perl command.pl -I <otv-IP> administrator <otv-password>`. Es necesario tener una sola cotización en torno al valor de la contraseña.
+
Se muestra un mensaje indicando que las credenciales de almacenamiento están almacenadas correctamente. El SRA puede comunicarse con el servidor SRA mediante la dirección IP, el puerto y las credenciales proporcionados.




