---
permalink: protect/task_configure_storage_replication_adapter_for_nas_environment.html 
sidebar: sidebar 
keywords:  
summary: 'Debe configurar los sistemas de almacenamiento antes de ejecutar el adaptador de replicación de almacenamiento \(SRA\) para VMware vCenter Site Recovery Manager \(SRM\).' 
---
= Configurar el adaptador de replicación de almacenamiento para el entorno NAS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe configurar los sistemas de almacenamiento antes de ejecutar Storage Replication Adapter (SRA) para VMware vCenter Site Recovery Manager (SRM).

*Lo que necesitará*

Debe haber instalado los siguientes programas en el sitio protegido y en el sitio de recuperación:

* SRM
+
Puede encontrar documentación sobre la instalación de SRM en el sitio de VMware.

+
https://www.vmware.com/support/pubs/srm_pubs.html["Documentación de VMware Site Recovery Manager"]

* SRA.
+
El adaptador se instala en el SRM y en el servidor SRA.



* Pasos*

. Compruebe que los almacenes de datos del sitio protegido contienen máquinas virtuales registradas en vCenter Server.
. Compruebe que los hosts ESXi del sitio protegido hayan montado los volúmenes NFS exporta de la máquina virtual de almacenamiento (SVM).
. Compruebe que las direcciones válidas, como la dirección IP, el nombre de host o el FQDN en el que están presentes las exportaciones NFS, se especifican en el campo *direcciones NFS* cuando se utiliza el asistente Array Manager para agregar matrices a SRM.
. Utilice el comando ping en cada host ESXi del sitio de recuperación para verificar que el host tiene un puerto de VMkernel que pueda acceder a las direcciones IP que se utilizan para servir exportaciones NFS desde la SVM.


https://mysupport.netapp.com/site/global/dashboard["Soporte de NetApp"]
