---
permalink: concepts/concept_virtual_storage_console_overview.html 
sidebar: sidebar 
keywords:  
summary: Las herramientas de ONTAP para VMware vSphere proporcionan una gestión del ciclo de vida integral para máquinas virtuales en entornos VMware que usan los sistemas de almacenamiento de NetApp. Permite a los administradores gestionar el almacenamiento desde el servidor de vCenter directamente y, por tanto, simplifica la gestión de datos y el almacenamiento para entornos VMware. 
---
= Descripción general de las herramientas de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las herramientas de ONTAP para VMware vSphere proporcionan una gestión del ciclo de vida integral para máquinas virtuales en entornos VMware que usan los sistemas de almacenamiento de NetApp. Permite a los administradores gestionar el almacenamiento desde el servidor de vCenter directamente y, por tanto, simplifica la gestión de datos y el almacenamiento para entornos VMware.

Las herramientas de ONTAP se integran con vSphere Client y permiten utilizar servicios de inicio de sesión único (SSO). En un entorno con varias instancias de vCenter Server, cada instancia de vCenter Server que desee gestionar debe tener su propia instancia registrada de las herramientas de ONTAP.

Cada componente de las herramientas de ONTAP ofrece funcionalidades para ayudarle a gestionar su almacenamiento de forma más eficiente.

La herramienta del complemento VMware vSphere Client está diseñada para integrar la funcionalidad del plugin en vSphere Client sin necesidad de ejecutarse dentro de vCenter Server. Esto ofrece aislamiento de complementos y permite la escalabilidad horizontal de complementos que funcionan en entornos vSphere grandes.



== Virtual Storage Console (VSC)

VSC le permite realizar las siguientes tareas:

* Añada controladoras de almacenamiento, asigne credenciales y configure permisos para las controladoras de almacenamiento de VSC, que tanto el proveedor de SRA como VASA puedan aprovechar
* Aprovisione los almacenes de datos
* Supervise el rendimiento de los almacenes de datos y las máquinas virtuales en el entorno vCenter Server
* Controle el acceso del administrador a los objetos de vCenter Server mediante el control de acceso basado en roles (RBAC) en dos niveles:
+
** Objetos de vSphere, como máquinas virtuales y almacenes de datos
+
Estos objetos se gestionan mediante el control de acceso basado en roles de vCenter Server.

** Y el almacenamiento de ONTAP
+
Los sistemas de almacenamiento se gestionan mediante RBAC de ONTAP.



* Consulte y actualice la configuración del host de los hosts ESXi conectados al almacenamiento de NetApp


Las operaciones de aprovisionamiento de VSC se benefician de usar el plugin de NFS para VMware vStorage APIs for Array Integration (VAAI). El plugin de NFS para VAAI es una biblioteca de software que integra las bibliotecas de discos virtuales de VMware que están instaladas en el host ESXi. El paquete VAAI de VMware permite descargar determinadas tareas de los hosts físicos a la cabina de almacenamiento. Puede realizar tareas como thin provisioning y la aceleración de hardware en el nivel de cabina para reducir la carga de trabajo en los hosts ESXi. La función de copia de liberación de sobrecarga y reserva de espacio mejoran el rendimiento de las operaciones de VSC.

El plugin de NetApp NFS para VAAI no se envía con VSC. Pero puede descargar el paquete de instalación del plugin y obtener las instrucciones de instalación del plugin en el sitio de soporte de NetApp.



== Proveedor de VASA

VASA Provider para ONTAP usa las API VMware vSphere para el reconocimiento del almacenamiento (VASA) para enviar información sobre el almacenamiento que utiliza VMware vSphere al vCenter Server. Las herramientas de ONTAP cuentan con VASA Provider integrado con VSC. EL proveedor DE VASA permite realizar las siguientes tareas:

* Aprovisione los almacenes de datos de VMware Virtual Volumes (vVols)
* Cree y utilice perfiles de capacidades de almacenamiento que definan diferentes objetivos de nivel de servicio (SLO) de almacenamiento para su entorno
* Compruebe que cumple las normativas entre los almacenes de datos y los perfiles de funcionalidad de almacenamiento
* Configure las alarmas para que le avise cuando los volúmenes y agregados se aproximen a los límites del umbral
* Supervise el rendimiento de los discos de máquinas virtuales (VMDK) y las máquinas virtuales que se crean en los almacenes de datos vVols




== Adaptador de replicación de almacenamiento (SRA)

Cuando se habilita el SRA y se usa junto con VMware Site Recovery Manager (SRM), es posible recuperar los almacenes de datos y las máquinas virtuales de vCenter Server en caso de fallo. El SRA permite utilizar la replicación basada en cabina (ABR) para sitios protegidos y sitios de recuperación para la recuperación ante desastres en caso de un fallo.

*Información relacionada*

https://mysupport.netapp.com/site/global/dashboard["Soporte de NetApp"]
