---
permalink: concepts/concept_standard_roles_packaged_with_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 'Para simplificar el uso de los privilegios de vCenter Server y el control de acceso basado en funciones \(RBAC\), Virtual Storage Console \(VSC\) proporciona roles VSC estándar que permiten realizar tareas clave de VSC. También hay un rol de solo lectura que le permite ver la información de VSC, pero no ejecutar tareas.' 
---
= Funciones estándar incluidas en las herramientas de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para simplificar el uso de los privilegios de vCenter Server y el control de acceso basado en roles (RBAC), Virtual Storage Console (VSC) ofrece roles VSC estándar que le permiten realizar tareas clave de VSC. También hay un rol de solo lectura que le permite ver la información de VSC, pero no ejecutar tareas.

Los roles estándar de VSC tienen privilegios específicos requeridos de VSC y los privilegios nativos de vCenter Server necesarios para que los usuarios ejecuten tareas de VSC. Además, los roles están configurados para contar con todos los privilegios necesarios en todas las versiones compatibles de vCenter Server.

El administrador puede asignar estos roles a los usuarios según sea necesario.


NOTE: Cuando actualiza VSC a la versión más reciente, los roles estándar se actualizan automáticamente para que funcionen con la nueva versión de VSC.

Para ver los roles estándar VSC, haga clic en *roles* en la página principal de vSphere Client.

Los roles que ofrece VSC permiten realizar las siguientes tareas:

|===


| *Rol* | *Descripción* 


 a| 
Administrador de VSC
 a| 
Ofrece todos los privilegios nativos de vCenter Server y los privilegios específicos de VSC requeridos para ejecutar todas las tareas de VSC.



 a| 
Solo lectura de VSC
 a| 
Proporciona acceso de solo lectura a VSC. Estos usuarios no pueden realizar ninguna acción VSC que esté controlada por el acceso.



 a| 
Aprovisionamiento de VSC
 a| 
Ofrece todos los privilegios nativos de vCenter Server y los privilegios específicos de VSC necesarios para aprovisionar almacenamiento. Es posible realizar las siguientes tareas:

* Crear nuevos almacenes de datos
* Destrucción de almacenes de datos
* Ver información sobre los perfiles de funcionalidad del almacenamiento


|===


== Directrices para usar roles estándar de VSC

Cuando trabaja con herramientas estándar de ONTAP para roles de VMware vSphere, hay ciertas directrices que deben seguir.

No debe modificar directamente los roles estándar. Si lo hace, VSC sobrescribirá los cambios cada vez que actualice VSC. El instalador actualiza las definiciones de rol estándar cada vez que actualiza VSC. Si hace esto, se garantiza que los roles sean actuales para la versión de VSC, así como para todas las versiones compatibles de vCenter Server.

Sin embargo, puede usar los roles estándar para crear roles que se ajusten a su entorno. Para ello, debe copiar el rol estándar de VSC y editar el rol copiado. Al crear un rol nuevo, puede mantener esta función incluso al reiniciar o actualizar el servicio VSC Windows.

Algunas de las formas de utilizar las funciones estándar de VSC incluyen las siguientes:

* Utilice los roles estándar de VSC para todas las tareas de VSC.
+
En esta situación, los roles estándar ofrecen todos los privilegios que un usuario necesita para realizar las tareas de VSC.

* Combinar roles para expandir las tareas que un usuario puede realizar.
+
Si los roles estándar de VSC proporcionan demasiada granularidad en el entorno, puede ampliar los roles creando grupos de nivel superior que contengan varias funciones.

+
Si un usuario tiene que ejecutar otras tareas que no son de VSC y requieren privilegios nativos de vCenter Server adicionales, puede crear una función que incluya esos privilegios y también añadirla al grupo.

* Cree funciones más detalladas.
+
Si su empresa necesita implementar funciones más restrictivas que las funciones estándar de VSC, puede usar los roles de VSC para crear nuevas funciones.

+
En este caso, debe clonar los roles de VSC necesarios y editar el rol clonado para que solo tenga los privilegios que requiere el usuario.


