---
permalink: concepts/concept_vcenter_server_role_based_access_control_features_in_vsc_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 'VCenter Server proporciona control de acceso basado en roles \(RBAC\) que permite controlar el acceso a los objetos de vSphere. En las herramientas de ONTAP para VMware vSphere, el control de acceso basado en roles de vCenter Server funciona con el control de acceso basado en roles de ONTAP para determinar qué tareas de herramientas de ONTAP puede ejecutar un usuario específico en un sistema de almacenamiento específico.' 
---
= Información general sobre el control de acceso basado en roles en las herramientas de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VCenter Server proporciona un control de acceso basado en roles (RBAC) que permite controlar el acceso a los objetos de vSphere. En las herramientas de ONTAP® para VMware vSphere, el control de acceso basado en roles de vCenter Server funciona con el control de acceso basado en roles de ONTAP para determinar qué tareas de herramientas de ONTAP puede realizar un usuario específico en objetos de un sistema de almacenamiento específico.

Para completar correctamente una tarea, debe tener los permisos de control de acceso basado en roles de vCenter Server correspondientes. Durante una tarea, las herramientas de ONTAP comprueban los permisos de vCenter Server de un usuario antes de comprobar los privilegios de ONTAP del usuario.

Es posible establecer los permisos de vCenter Server para el objeto raíz (también denominado carpeta raíz). Posteriormente, es posible refinar la seguridad aplicando restricciones a entidades secundarias que no necesitan los mismos permisos.
