---
permalink: concepts/concept_virtual_storage_console_overview.html 
sidebar: sidebar 
keywords:  
summary: Las herramientas de ONTAP para VMware vSphere permiten gestionar su ciclo de vida de extremo a extremo para máquinas virtuales en entornos VMware que usan los sistemas de almacenamiento de NetApp. Simplifica el almacenamiento y la gestión de datos en entornos VMware al permitir que los administradores gestionen directamente el almacenamiento en vCenter Server. 
---
= Descripción general de las herramientas de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las herramientas de ONTAP para VMware vSphere permiten gestionar su ciclo de vida de extremo a extremo para máquinas virtuales en entornos VMware que usan los sistemas de almacenamiento de NetApp. Simplifica el almacenamiento y la gestión de datos en entornos VMware al permitir que los administradores gestionen directamente el almacenamiento en vCenter Server.

Con vSphere 6.5, VMware presentó un nuevo cliente basado en HTML5 llamado vSphere Client. Las versiones 9.6 y posteriores de herramientas de ONTAP admiten solo vSphere Client. Las herramientas de ONTAP se integran con vSphere Client y permiten utilizar servicios de inicio de sesión único (SSO). En un entorno con varias instancias de vCenter Server, cada instancia de vCenter Server que desea gestionar debe tener su propia instancia registrada de VSC.

Cada componente de las herramientas de ONTAP ofrece funcionalidades para ayudarle a gestionar su almacenamiento de forma más eficiente.



== Virtual Storage Console (VSC)

VSC le permite realizar las siguientes tareas:

* Añada controladoras de almacenamiento, asigne credenciales y configure permisos para las controladoras de almacenamiento de VSC, que tanto el proveedor de SRA como VASA puedan aprovechar
* Aprovisione los almacenes de datos
* Supervise el rendimiento de los almacenes de datos y las máquinas virtuales en el entorno vCenter Server
* Controle el acceso del administrador a los objetos de vCenter Server mediante el control de acceso basado en roles (RBAC) en dos niveles:
+
** Objetos de vSphere, como máquinas virtuales y almacenes de datos
+
Estos objetos se gestionan mediante el control de acceso basado en roles de vCenter Server.

** Y el almacenamiento de ONTAP
+
Los sistemas de almacenamiento se gestionan mediante RBAC de ONTAP.



* Consulte y actualice la configuración del host de los hosts ESXi conectados al almacenamiento de NetApp


Las operaciones de aprovisionamiento de VSC se benefician de usar el plugin de NFS para VMware vStorage APIs for Array Integration (VAAI). El plugin de NFS para VAAI es una biblioteca de software que integra las bibliotecas de discos virtuales de VMware que están instaladas en el host ESXi. El paquete VAAI de VMware permite descargar determinadas tareas de los hosts físicos a la cabina de almacenamiento. Puede realizar tareas como thin provisioning y la aceleración de hardware en el nivel de cabina para reducir la carga de trabajo en los hosts ESXi. La función de copia de liberación de sobrecarga y reserva de espacio mejoran el rendimiento de las operaciones de VSC.

El plugin de NetApp NFS para VAAI no se envía con VSC. Pero puede descargar el paquete de instalación del plugin y obtener las instrucciones de instalación del plugin en el sitio de soporte de NetApp.



== Proveedor de VASA

VASA Provider para ONTAP usa las API VMware vSphere para el reconocimiento del almacenamiento (VASA) para enviar información sobre el almacenamiento que utiliza VMware vSphere al vCenter Server. Las herramientas de ONTAP cuentan con VASA Provider integrado con VSC. EL proveedor DE VASA permite realizar las siguientes tareas:

* Aprovisione los almacenes de datos de VMware Virtual Volumes (vVols)
* Cree y utilice perfiles de capacidades de almacenamiento que definan diferentes objetivos de nivel de servicio (SLO) de almacenamiento para su entorno
* Compruebe que cumple las normativas entre los almacenes de datos y los perfiles de funcionalidad de almacenamiento
* Configure las alarmas para que le avise cuando los volúmenes y agregados se aproximen a los límites del umbral
* Supervise el rendimiento de los discos de máquinas virtuales (VMDK) y las máquinas virtuales que se crean en los almacenes de datos vVols


Si utiliza ONTAP 9.6 o una versión anterior, el proveedor de VASA se comunica con vCenter Server mediante las API de VASA y se comunica con ONTAP mediante las API de NetApp denominadas ZAPI. Para ver la consola vVols de ONTAP 9.6 y versiones anteriores, debe haber instalado y registrado servicios de API de OnCommand en vCenter Server. Si utiliza ONTAP 9.7 y versiones posteriores, no requiere que los servicios API de OnCommand se registren en VASA Provider para ver el panel vVols.


NOTE: Para ONTAP 9.6 y versiones anteriores, VASA Provider requiere una instancia dedicada de servicios API de OnCommand. Una instancia de los servicios de API de OnCommand no se puede compartir con varias instancias de proveedor VASA.



== Adaptador de replicación de almacenamiento (SRA)

Cuando se habilita el SRA y se usa junto con VMware Site Recovery Manager (SRM), es posible recuperar los almacenes de datos y las máquinas virtuales de vCenter Server en caso de fallo. El SRA permite utilizar la replicación basada en cabina (ABR) para sitios protegidos y sitios de recuperación para la recuperación ante desastres en caso de un fallo.

*Información relacionada*

https://mysupport.netapp.com/site/global/dashboard["Soporte de NetApp"]
