---
permalink: concepts/concept_configure_high_availability_for_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 'Las herramientas de ONTAP son compatibles con una configuración de alta disponibilidad \(ha\) para ayudar a proporcionar la funcionalidad ininterrumpida de las herramientas de ONTAP durante un fallo.' 
---
= Configurar la alta disponibilidad para las herramientas de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las herramientas de ONTAP son compatibles con una configuración de alta disponibilidad (ha) para ayudar a proporcionar la funcionalidad sin interrupciones de las herramientas de ONTAP durante el fallo.

Las herramientas de ONTAP se basan en la función de alta disponibilidad (ha) de VMware vSphere y en la función de tolerancia a fallos (FT) de vSphere para proporcionar una alta disponibilidad. La solución de alta disponibilidad permite recuperarse rápidamente de las interrupciones provocadas por:

* Error del host
* Fallo de red
* Fallo de máquina virtual (fallo de SO invitado)
* Fallo de la aplicación (herramientas ONTAP)


No se necesita ninguna configuración adicional para que las herramientas de ONTAP proporcionen una alta disponibilidad. Solo las instancias de vCenter Server y los hosts ESXi deben configurarse con la función de alta disponibilidad de VMware vSphere o la función vSphere FT en función de sus requisitos. Tanto la alta disponibilidad COMO FT requieren hosts en clúster junto con almacenamiento compartido. FT tiene requisitos y limitaciones adicionales.

Además de la solución de alta disponibilidad de VMware vSphere y la solución VSPHERE FT, las herramientas de ONTAP también contribuyen a que los servicios de herramientas de ONTAP se ejecuten en todo momento. El proceso de vigilancia de las herramientas ONTAP supervisa periódicamente los tres servicios y los reinicia automáticamente cuando se detecta cualquier tipo de fallo. Esto ayuda a evitar que se produzcan fallos en las aplicaciones.


NOTE: Las herramientas de ONTAP no admiten la alta disponibilidad del vCenter.



== VMware vSphere ha

Puede configurar su entorno de vSphere donde las herramientas de ONTAP para VMware vSphere esté puesto en marcha para una alta disponibilidad (ha). La función de alta disponibilidad de VMware ofrece protección tras fallos frente a fallos del hardware y fallos del sistema operativo en entornos virtuales.

La función de alta disponibilidad de VMware supervisa las máquinas virtuales para detectar fallos del sistema operativo y fallos del hardware. Cuando se detecta un fallo, la función de alta disponibilidad de VMware reinicia las máquinas virtuales en los demás servidores físicos del pool de recursos. No es necesaria la intervención manual cuando se detecta un fallo del servidor.

El procedimiento para configurar VMware ha depende de la versión de su vCenter Server. Por ejemplo, puede utilizar el siguiente enlace de referencia y seleccionar la versión necesaria de vCenter Server para ver los pasos necesarios para configurar la alta disponibilidad de VMware.

https://docs.vmware.com/en/VMware-vSphere/8.0/vsphere-availability/GUID-5432CA24-14F1-44E3-87FB-61D937831CF6.html["Documentación de VMware vSphere: Crear y usar clústeres de alta disponibilidad de vSphere"]



== Tolerancia a fallos de VMware vSphere

La función DE tolerancia a fallos (FT) de VMware vSphere proporciona alta disponibilidad (ha) a un nivel superior y le permite proteger las máquinas virtuales sin perder datos o conexiones. Debe habilitar o deshabilitar las herramientas de vSphere FT para ONTAP desde vCenter Server.

Asegúrese de que la licencia de vSphere sea compatible CON FT con el número de vCPU necesarias para herramientas ONTAP en su entorno (al menos 2 vCPU y 4 vCPU para entornos a gran escala).

VSphere FT permite que las máquinas virtuales funcionen continuamente incluso durante fallos de servidores. Cuando se habilita vSphere FT en una máquina virtual, se crea automáticamente una copia de la máquina virtual primaria en otro host (la máquina virtual secundaria) seleccionado por Distributed Resource Scheduler (DRS). Si DRS no está habilitado, el host de destino se selecciona de entre los hosts disponibles. VSphere FT opera la máquina virtual principal y la máquina virtual secundaria en modo de bloqueo, con cada mirroring del estado de ejecución de la máquina virtual principal a la máquina virtual secundaria.

Cuando se produce un error de hardware que provoca un fallo en la máquina virtual primaria, la máquina virtual secundaria recupera inmediatamente dónde se detuvo la máquina virtual principal. La máquina virtual secundaria continúa ejecutándose sin pérdida de conexiones de red, transacciones o datos.

El sistema debe cumplir los requisitos de CPU, los requisitos de límite de máquinas virtuales y los requisitos de licencias para configurar vSphere FT para la instancia de vCenter Server.

El procedimiento para configurar la alta disponibilidad depende de la versión del servidor de vCenter Server. Por ejemplo, puede utilizar el siguiente enlace de referencia y seleccionar la versión necesaria de vCenter Server para ver los pasos necesarios para configurar la alta disponibilidad.

https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.avail.doc/GUID-57929CF0-DA9B-407A-BF2E-E7B72708D825.html["Documentación de VMware vSphere: Requisitos, límites y licencias de Fault Tolerance"]
