---
permalink: concepts/reference_metrocluster_configurations_supported_by_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: Las herramientas de ONTAP para VMware vSphere son compatibles con entornos que usan configuraciones de MetroCluster IP y FC para ONTAP. La mayor parte de este soporte es automático. Sin embargo, es posible que note algunas diferencias cuando utiliza un entorno de MetroCluster con VSC y VASA Provider. 
---
= Configuraciones de MetroCluster compatibles con las herramientas de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las herramientas de ONTAP para VMware vSphere son compatibles con entornos que usan configuraciones de MetroCluster IP y FC para ONTAP. La mayor parte de este soporte es automático. Sin embargo, es posible que note algunas diferencias cuando utiliza un entorno de MetroCluster con VSC y VASA Provider.


NOTE: El SRA no es compatible con las configuraciones de MetroCluster.



== Configuraciones de MetroCluster y VSC

Debe asegurarse de que VSC detecte las controladoras del sistema de almacenamiento en el sitio primario y en el sitio secundario. Generalmente, VSC detecta automáticamente las controladoras de almacenamiento. Si utiliza una LIF de gestión de clústeres, es una buena práctica verificar que VSC ha detectado los clústeres en ambos sitios. De lo contrario, puede añadir manualmente las controladoras de almacenamiento a VSC. También puede modificar el nombre de usuario y las parejas de contraseñas que utiliza VSC para conectarse a las controladoras de almacenamiento.

Cuando se produce una conmutación, los SVM del sitio secundario toman el control. Estos SVMs tienen adjunto el sufijo "'-mc'" a sus nombres. Si se produce una operación de conmutación de sitios mientras realiza operaciones como el aprovisionamiento de un almacén de datos, el nombre de la SVM en la que reside el almacén de datos se modifica para incluir el sufijo "'-mc". Este sufijo se descarta cuando se produzca la conmutación de estado y las SVM del sitio principal reanudan el control.


NOTE: Si ha añadido SVM directas con la configuración de MetroCluster a VSC, tras la conmutación, no se verá reflejado el cambio en el nombre de SVM (además del sufijo "'-mc"). El resto de las operaciones de conmutación se siguen ejecutando con normalidad.

Cuando se produce una conmutación de sitios o una conmutación de estado, VSC puede tardar unos minutos en detectar y detectar los clústeres automáticamente. Si esto sucede mientras realiza una operación VSC, como el aprovisionamiento de un almacén de datos, es posible que experimente una demora.



== Configuraciones de MetroCluster y proveedor VASA

VASA Provider admite automáticamente entornos que utilizan configuraciones MetroCluster. El cambio es transparente en los entornos de proveedores de VASA. No puede añadir SVM directas a VASA Provider.


NOTE: VASA Provider no incorpora el sufijo "'-mc" a los nombres de las SVM del sitio secundario después de una conmutación por sitios.
