---
permalink: configure/concept_configure_storage_capability_profiles.html 
sidebar: sidebar 
keywords: storage capability profiles 
summary: EL proveedor VASA para ONTAP permite crear perfiles de funcionalidad de almacenamiento y asignarlos a su almacenamiento. Esto le ayuda a mantener la coherencia en todo el almacenamiento. También puede usar VASA Provider para comprobar el cumplimiento de normativas entre el almacenamiento y los perfiles de capacidades de almacenamiento. 
---
= Información general de los perfiles de funcionalidad de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
EL proveedor VASA para ONTAP permite crear perfiles de funcionalidad de almacenamiento y asignarlos a su almacenamiento. Esto ayuda a mantener la coherencia en todo el almacenamiento. También puede usar VASA Provider para comprobar el cumplimiento de normativas entre el almacenamiento y los perfiles de capacidades de almacenamiento.

Una funcionalidad de almacenamiento es un conjunto de atributos del sistema de almacenamiento que identifica un nivel específico de rendimiento del almacenamiento, eficiencia del almacenamiento y otras funcionalidades, como el cifrado del objeto de almacenamiento asociado con la funcionalidad de almacenamiento.

Para los almacenes de datos tradicionales, puede utilizar un perfil de funcionalidad de almacenamiento para crear almacenes de datos de forma coherente con los atributos comunes y asignar políticas de calidad de servicio a ellos. Durante el aprovisionamiento, las herramientas de ONTAP muestran los clústeres, las SVM y los agregados que coinciden con el perfil de funcionalidad de almacenamiento. Puede generar un perfil de capacidad de almacenamiento a partir de almacenes de datos tradicionales existentes mediante la opción *GLOBAL AUTO-GENERATE PROFILES* del menú Storage Mapping. Después de crear el perfil, puede utilizar las herramientas de ONTAP para supervisar el cumplimiento de los almacenes de datos con el perfil.


NOTE: El usuario de SVM no admite los almacenes de datos de VVol.

Si se utiliza con almacenes de datos vVols, el asistente de aprovisionamiento puede utilizar varios perfiles de funcionalidad de almacenamiento para crear diferentes volúmenes FlexVol en el almacén de datos. Puede utilizar la normativa de almacenamiento de equipos virtuales para crear automáticamente vVols para una máquina virtual en los volúmenes FlexVol adecuados, tal y como se ha definido. Por ejemplo, puede crear perfiles para clases de almacenamiento comunes (como límites de rendimiento y otras funcionalidades como el cifrado o FabricPool). Posteriormente, es posible crear políticas de almacenamiento de equipos virtuales en vCenter Server que representen a los tipos de negocio de las máquinas virtuales y vincularlos al perfil de funcionalidad de almacenamiento correspondiente por nombre (por ejemplo, producción, pruebas, recursos humanos).

Si se utiliza con vVols, también se utiliza el perfil de funcionalidad del almacenamiento para establecer el rendimiento del almacenamiento para el equipo virtual individual y colocarlo en el volumen FlexVol en el almacén de datos vVols que mejor satisfaga los requisitos de rendimiento. Puede especificar la política de calidad de servicio con IOPS mínimo y/o máximo para el rendimiento. Puede usar las políticas predeterminadas al aprovisionar una máquina virtual inicialmente, o cambiar la política de almacenamiento de máquinas virtuales más adelante si cambian los requisitos empresariales.


NOTE: El perfil de funcionalidad de almacenamiento ASA-C es compatible con las herramientas de ONTAP para VMware vSphere 9.13P1 en adelante.

Los perfiles de funcionalidad de almacenamiento predeterminados para esta versión de herramientas de ONTAP:

* Platinum_AFF_A
* Platinum_AFF_C
* Platinum_ASA_A
* Platinum_ASA_C
* AFF_NVME_AFF_A
* AFF_NVME_AFF_C
* AFF_NVME_ASA_A
* AFF_NVME_ASA_C
* AFF_THICK_AFF_A
* AFF_THICK_AFF_C
* AFF_THICK_ASA_A
* AFF_THICK_ASA_C
* AFF_DEFAULT_AFF_A
* AFF_DEFAULT_AFF_C
* AFF_DEFAULT_ASA_A
* AFF_DEFAULT_ASA_C
* AFF_TIERING_AFF_A
* AFF_TIERING_AFF_C
* AFF_TIERING_ASA_A
* AFF_TIERING_ASA_C
* AFF_ENCRYPTED_AFF_A
* AFF_ENCRYPTED_AFF_C
* AFF_ENCRYPTED_ASA_A
* AFF_ENCRYPTED_ASA_C
* AFF_Encrypted_Tiering_AFF_A
* AFF_Encrypted_Tiering_AFF_C
* AFF_Encrypted_Tiering_ASA_A
* AFF_Encrypted_Tiering_ASA_C
* AFF_Encrypted_min50_AFF_A
* AFF_Encrypted_min50_AFF_C
* AFF_Encrypted_min50_ASA_A
* AFF_Encrypted_min50_ASA_C
* Bronce


A continuación, vCenter Server asocia la funcionalidad de almacenamiento de un LUN o un volumen con el almacén de datos que se aprovisiona en ese LUN o volumen. Esto permite aprovisionar una máquina virtual en un almacén de datos que coincida con el perfil de almacenamiento de la máquina virtual y garantizar que todos los almacenes de datos de un clúster de almacenes de datos tengan los mismos niveles de servicio de almacenamiento.

Con las herramientas de ONTAP, puede configurar cada almacén de datos de volúmenes virtuales (vVols) con un nuevo perfil de funcionalidad de almacenamiento que permita aprovisionar máquinas virtuales con requisitos de IOPS variables en el mismo almacén de datos vVols. Al ejecutar el flujo de trabajo de aprovisionamiento de equipos virtuales con requisitos de IOPS, todos los almacenes de datos vVols se enumeran en la lista de almacenes de datos compatibles.



== Consideraciones que tener en cuenta para crear y editar perfiles de funcionalidad de almacenamiento

Debe tener en cuenta las consideraciones que se deben tener en cuenta para crear y editar perfiles de funcionalidad de almacenamiento.

* Solo puede configurar Min IOPS en sistemas AFF.
* Es posible configurar métricas de calidad de servicio en un almacén de datos de volumen virtual (vVols).
+
Esta funcionalidad proporciona una mayor flexibilidad a la hora de asignar diferentes métricas de calidad de servicio para diferentes VMDK de la misma máquina virtual que se aprovisiona en un almacén de datos virtual.

* Es posible configurar perfiles de capacidades de almacenamiento para almacenes de datos de cabina flash híbrida, ASA y AFF.
+
En los sistemas de cabina flash híbrida, ASA y AFF, se puede configurar la reserva de espacio para que sea gruesa o delgada.

* Puede usar perfiles de funcionalidad de almacenamiento para proporcionar cifrado para los almacenes de datos.
* No puede modificar los perfiles de funcionalidad de almacenamiento existentes (creados antes de la versión 7.2) después de actualizar desde una versión anterior de las herramientas de ONTAP para VMware vSphere a la versión más reciente de las herramientas de ONTAP.
+
Los perfiles de funcionalidad de almacenamiento anteriores se conservan para su compatibilidad con versiones anteriores. Si no se están utilizando las plantillas predeterminadas, durante la actualización a la versión más reciente de las herramientas de ONTAP, las plantillas existentes se anularán para reflejar las nuevas métricas de calidad de servicio y las políticas de organización en niveles relacionadas con el rendimiento de los perfiles de funcionalidades de almacenamiento.

* No es posible modificar ni utilizar los perfiles de funcionalidad de almacenamiento heredados para aprovisionar nuevos almacenes de datos virtuales ni políticas de almacenamiento de máquinas virtuales.

