---
permalink: configure/concept_configure_storage_systems_for_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: Debe añadir sistemas de almacenamiento a las herramientas de ONTAP y establecer credenciales predeterminadas, si es necesario, mediante la interfaz de herramientas de ONTAP. 
---
= Información general de los sistemas de almacenamiento para las herramientas de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe añadir sistemas de almacenamiento a las herramientas de ONTAP y establecer credenciales predeterminadas, si es necesario, mediante la interfaz de herramientas de ONTAP.

Las herramientas de ONTAP para VMware vSphere ofrecen un único mecanismo para detectar sistemas de almacenamiento y configurar las credenciales de almacenamiento. Las credenciales proporcionan los permisos de ONTAP requeridos para permitir que los usuarios de herramientas de ONTAP ejecuten tareas mediante los sistemas de almacenamiento.

Para que las herramientas de ONTAP puedan mostrar y gestionar los recursos de almacenamiento, las herramientas de ONTAP deben detectar los sistemas de almacenamiento. Como parte del proceso de detección, debe suministrar las credenciales de ONTAP para los sistemas de almacenamiento. Estos son los privilegios (o roles) asociados con el nombre de usuario y la pareja de contraseñas que se asignan a cada sistema de almacenamiento. Estas parejas de nombres de usuario y contraseñas utilizan el control de acceso basado en roles (RBAC) de ONTAP y deben configurarse desde ONTAP. Estas credenciales no se pueden cambiar desde las herramientas de ONTAP. Es posible definir roles de RBAC de ONTAP mediante System Manager de ONTAP.


NOTE: Si inicia sesión como administrador, tiene automáticamente todos los privilegios de ese sistema de almacenamiento.

Cuando se añade un sistema de almacenamiento a herramientas ONTAP, se debe proporcionar una dirección IP para el sistema de almacenamiento y la pareja de nombre de usuario y contraseña que está asociada con ese sistema. Puede configurar credenciales predeterminadas que las herramientas de ONTAP utilizarán durante el proceso de detección del sistema de almacenamiento, o bien puede introducir credenciales manualmente al detectar el sistema de almacenamiento. Los detalles del sistema de almacenamiento que se añaden a las herramientas de ONTAP se aplican automáticamente a las extensiones que habilita en la implementación. No es necesario añadir manualmente el almacenamiento al proveedor VASA y al adaptador de replicación de almacenamiento (SRA). Tanto las herramientas de ONTAP como el SRA admiten la adición de credenciales a nivel de clúster y a nivel de máquina virtual de almacenamiento (SVM). El proveedor DE VASA de solo admite credenciales en el nivel del clúster para añadir sistemas de almacenamiento. Cuando se añade un sistema de almacenamiento, cualquier comunicación entre el plugin de herramientas de ONTAP y el sistema de almacenamiento se debe autenticar mutuamente.

Si el entorno incluye varias instancias de vCenter Server, al añadir un sistema de almacenamiento a las herramientas ONTAP desde la página Storage Systems, el cuadro de diálogo Add Storage System muestra un cuadro de diálogo de vCenter Server en el que puede especificar la instancia de vCenter Server a la que debe añadirse el sistema de almacenamiento. Si añade un sistema de almacenamiento haciendo clic con el botón derecho en el nombre de un centro de datos, no tiene la opción de especificar una instancia de vCenter Server debido a que el servidor ya está asociado a ese centro de datos.

La detección se realiza de una de las siguientes maneras. En cada caso, debe proporcionar credenciales para todos los sistemas de almacenamiento recién detectados.

* Cuando se inicia el servicio ONTAP tools, las herramientas ONTAP inician su proceso de detección automática en segundo plano.
* Puede hacer clic en EL botón REDISCOVER All en la página *sistemas de almacenamiento*, o en un host o centro de datos para seleccionarlo en el menú *acciones* ( *acciones* > *herramientas ONTAP de NetApp* > *Actualizar datos de host y almacenamiento* ). También puede hacer clic en *DESCUBRIR* en la pestaña *Introducción* de la sección 'Descripción general'.


Todas las funciones de las herramientas de ONTAP requieren permisos específicos para realizar tareas. Es posible limitar qué pueden hacer los usuarios según las credenciales asociadas con el rol ONTAP. Todos los usuarios que tienen el mismo nombre de usuario del sistema de almacenamiento y la pareja de contraseñas comparten el mismo conjunto de credenciales del sistema de almacenamiento y pueden ejecutar las mismas operaciones.
