---
permalink: configure/reference_configure_guest_operating_system_scripts.html 
sidebar: sidebar 
keywords: Guest operating system 
summary: 'Las imágenes ISO de los scripts \(OS\) de sistemas operativos invitados se montan en las herramientas de ONTAP para el servidor VMware vSphere. Para utilizar los scripts del sistema operativo invitado para configurar los tiempos de espera de almacenamiento de las máquinas virtuales, se deben montar los scripts desde vSphere Client.' 
---
= Configurar los scripts del sistema operativo invitado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las imágenes ISO de los scripts de sistema operativo invitado se montan en herramientas para VMware vSphere Server. Para utilizar los scripts del sistema operativo invitado para configurar los tiempos de espera de almacenamiento de las máquinas virtuales, se deben montar los scripts desde vSphere Client.

|===


| *Tipo de sistema operativo* | *ajustes de tiempo de espera de 60 segundos* | *ajustes de tiempo de espera de 190 segundos* 


 a| 
Linux
 a| 
\https://<appliance_ip>:8143/vsc/public/writable/linux_gos_timeout-install.iso
 a| 
\https://<appliance_ip>:8143/vsc/public/writable/linux_gos_timeout_190-install.iso



 a| 
Windows
 a| 
\https://<appliance_ip>:8143/vsc/public/writable/windows_gos_timeout.iso
 a| 
\https://<appliance_ip>:8143/vsc/public/writable/windows_gos_timeout_190.iso



 a| 
Solaris
 a| 
\https://<appliance_ip>:8143/vsc/public/writable/solaris_gos_timeout-install.iso
 a| 
\https://<appliance_ip>:8143/vsc/public/writable/solaris_gos_timeout_190-install.iso

|===
Debe instalar el script desde la copia de la instancia de herramientas de ONTAP que está registrada en la instancia de vCenter Server (ELM) que gestiona la máquina virtual. Si su entorno incluye varias instancias de vCenter Server, debe seleccionar la instancia que contenga la máquina virtual para la que desea configurar los valores de tiempo de espera del almacenamiento.

Debe iniciar sesión en la máquina virtual y ejecutar el script para configurar los valores de tiempo de espera de almacenamiento.
