---
permalink: configure/reference_configure_the_vsc_preferences_files.html 
sidebar: sidebar 
keywords: preferences files 
summary: Los archivos de preferencias contienen configuraciones que controlan las herramientas de ONTAP® para las operaciones de VMware vSphere. En la mayoría de los casos, no es necesario modificar la configuración de estos archivos. Es útil saber qué archivos de preferencias utilizan las herramientas de ONTAP. 
---
= Configure los archivos de preferencias de herramientas de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los archivos de preferencias contienen configuraciones que controlan las herramientas de ONTAP para las operaciones de VMware vSphere. En la mayoría de los casos, no es necesario modificar la configuración de estos archivos. Es útil saber qué archivos de preferencias utilizan las herramientas de ONTAP.

Las herramientas de ONTAP tienen varios archivos de preferencias. Estos archivos incluyen claves de entrada y valores que determinan cómo las herramientas de ONTAP realizan diversas operaciones. Los siguientes son algunos de los archivos de preferencias que utiliza ONTAP Tools:

`/opt/netapp/vscserver/etc/kamino/kaminoprefs.xml`

`/opt/netapp/vscserver/etc/vsc/vscPreferences.xml`

Puede que tenga que modificar los archivos de preferencias en determinadas situaciones. Por ejemplo, si utiliza iSCSI, NFS o NVMe/FC y la subred es diferente entre los hosts ESXi y el sistema de almacenamiento, debe modificar los archivos de preferencias. Si no modifica la configuración del archivo de preferencias, se produce un error en el aprovisionamiento del almacén de datos porque las herramientas de ONTAP no pueden montar el almacén de datos.
