---
permalink: configure/task_automatically_generating_scps.html 
sidebar: sidebar 
keywords:  
summary: EL proveedor DE VASA para ONTAP permite generar automáticamente perfiles de funcionalidad de almacenamiento para los almacenes de datos tradicionales existentes. Cuando se selecciona la opción de generación automática para un almacén de datos, VASA Provider crea un perfil que contiene las capacidades de almacenamiento que utiliza ese almacén de datos. 
---
= Generar perfiles de funcionalidad de almacenamiento automáticamente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
EL proveedor DE VASA para ONTAP permite generar automáticamente perfiles de funcionalidad de almacenamiento para los almacenes de datos tradicionales existentes. Cuando se selecciona la opción de generación automática para un almacén de datos, VASA Provider crea un perfil que contiene las capacidades de almacenamiento que utiliza ese almacén de datos.

*Lo que necesitará*

* Debe haber registrado la instancia del proveedor de VASA con las herramientas ONTAP.
* Las herramientas de ONTAP deben haber detectado tu almacenamiento.


*Acerca de esta tarea*

Después de crear un perfil de funcionalidad de almacenamiento, puede modificar el perfil para incluir más funcionalidades. El asistente para crear perfiles de funcionalidad de almacenamiento proporciona información sobre las funcionalidades que se pueden incluir en un perfil.

* Pasos*

. En la página de inicio de las herramientas NetApp ONTAP, haga clic en *Asignación de almacenamiento*.
. Seleccione el almacén de datos de la lista Available.
. En el menú acciones, seleccione *generación automática*.
. Cuando finalice el proceso de generación automática, actualice la pantalla para ver información sobre el nuevo perfil.
+
El nuevo perfil aparece en la columna de perfil asociado. El nombre del nuevo perfil se basa en los recursos del perfil. Si es necesario, puede cambiar el nombre del perfil.


