---
permalink: configure/task_set_default_credentials_for_storage_systems.html 
sidebar: sidebar 
keywords:  
summary: Puede usar las herramientas de ONTAP® para VMware vSphere a fin de configurar credenciales predeterminadas para un sistema de almacenamiento en el servidor vCenter. 
---
= Establezca las credenciales predeterminadas para los sistemas de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede usar herramientas de ONTAP para VMware vSphere a fin de establecer las credenciales predeterminadas para un sistema de almacenamiento en el para vCenter Server.

*Lo que necesitará*

Debe haber seleccionado la instancia de vCenter Server que desea utilizar para crear credenciales predeterminadas.

*Acerca de esta tarea*

Si configura credenciales predeterminadas para los sistemas de almacenamiento, las herramientas de ONTAP utilizan estas credenciales para iniciar sesión en un sistema de almacenamiento que las herramientas de ONTAP acaban de detectar. Si las credenciales predeterminadas no funcionan, debe iniciar sesión manualmente en el sistema de almacenamiento. Las herramientas de ONTAP y el SRA admiten la adición de credenciales del sistema de almacenamiento a nivel de clúster o a nivel de SVM. Sin embargo, el proveedor de VASA solo funcionará con las credenciales en el nivel del clúster.

* Pasos*

. En la página Inicio de las herramientas de ONTAP, haga clic en *Configuración* > *Configuración administrativa* > *Configurar credenciales predeterminadas para el sistema de almacenamiento*.
. En el cuadro de diálogo Storage System Default Credentials, introduzca el nombre de usuario y la contraseña para el sistema de almacenamiento.
+
Las credenciales de la controladora de almacenamiento se asignan en ONTAP según el nombre de usuario y la pareja de contraseñas. Las credenciales de la controladora de almacenamiento pueden ser la cuenta de administrador o una cuenta personalizada que utilice el control de acceso basado en roles (RBAC).

+
No se pueden usar herramientas de ONTAP para cambiar los roles asociados con el nombre de usuario y la pareja de contraseñas de la controladora de almacenamiento. Para modificar o crear un nuevo rol de usuario de ONTAP y usarlo con herramientas de ONTAP, es posible usar System Manager.

+
Consulte link:..configure/task_configure_user_role_and_privileges.html["Configure los roles y privilegios de usuario"]sección.

. Haga clic en *Aceptar* para guardar las credenciales predeterminadas.


Si actualizó las credenciales del sistema de almacenamiento porque se informó sobre un sistema de almacenamiento `Authentication Failure` Estado, debe hacer clic en la opción *REDESCUBRIR TODO* disponible en la página Sistemas de Almacenamiento. Cuando hace esto, las herramientas de ONTAP intentan conectarse al sistema de almacenamiento usando las nuevas credenciales.
