---
permalink: configure/task_modify_storage_system.html 
sidebar: sidebar 
keywords:  
summary: Debe actualizar el certificado cuando caduque o cuando se modifique manualmente. Cuando el certificado de cliente o del clúster caduca o no coincide, se interrumpe la comunicación con el sistema ONTAP. 
---
= Modificar los sistemas de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilice el siguiente procedimiento para modificar los sistemas de almacenamiento.

* Pasos*

. En *Herramientas del ONTAP de NetApp*, selecciona *Sistemas de almacenamiento*.
. Haga clic en el botón Sistema de almacenamiento *Acción disponible* (tres puntos verticales) donde desea actualizar el certificado.
. Seleccione *Modificar*.
+

NOTE: Se recomienda que antes de que caduque el clúster o el certificado de cliente, obtenga el certificado renovado de ONTAP o genere el certificado de cliente de las herramientas de ONTAP para VMware vSphere.

. En la ventana *Modificar sistema de almacenamiento*, en el campo *Cargar certificado*, *Examinar* hasta la ubicación donde se almacena el certificado ONTAP y cargarlo.
+
Para certificado de clúster:

+
** Si modificó el certificado de clúster en ONTAP, deberá cargar manualmente el certificado modificado a las herramientas de ONTAP. Este es un paso obligatorio.
** Cuando el certificado de clúster ha caducado, el estado del sistema de almacenamiento cambia a Certificado de clúster caducado. Cuando el certificado de clúster caduca, el administrador de almacenamiento necesita generar el nuevo certificado en el lado ONTAP. La ventana *Modificar sistema de almacenamiento* recupera automáticamente el certificado de clúster del almacenamiento ONTAP y necesita autorizar el certificado de clúster.


. Cuando el certificado de cliente caduca, el estado del sistema de almacenamiento cambia a Certificado de cliente caducado.
+
Si el certificado de cliente ha caducado, en la ventana *Modificar sistema de almacenamiento*, seleccione la opción *Generar un nuevo certificado de cliente para ONTAP* para regenerar el certificado.



Una vez instalados los certificados, se restaura la comunicación con ONTAP.
