---
permalink: configure/task_register_oncommand_api_services_with_ontap_tools.html 
sidebar: sidebar 
keywords: virtual volume datastores 
summary: 'Si utiliza ONTAP 9.6 o una versión anterior, el panel de vVols puede mostrar los detalles de los almacenes de datos \(vVols\) de VMware Virtual Volumes y las máquinas virtuales solo si ha registrado el proveedor de servicios API de OnCommand para VASA para obtener datos para los informes de la máquina virtual vVols y el almacén de datos.' 
---
= Registre los servicios de API de OnCommand con las herramientas de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si utiliza ONTAP 9.6 o una versión anterior, el panel de vVols puede mostrar los detalles de los almacenes de datos de VMware Virtual Volumes (vVols) y las máquinas virtuales solo si ha registrado el proveedor de servicios de API de OnCommand para VASA para obtener datos para el equipo virtual vVols y los informes de almacenes de datos.

*Lo que necesitará*

Debe haber descargado los servicios de API de OnCommand 2.1 o una versión posterior del sitio de soporte de NetApp.


NOTE: La consola de vVols muestra métricas de rendimiento solo cuando los almacenes de datos de SAN vVols y las máquinas virtuales están configuradas con ONTAP 9,7 o posterior.

* Pasos*

. En la página de inicio de las herramientas de ONTAP, haga clic en *Configuración*.
. Haga clic en *Administrar extensión* en la ficha Configuración administrativa.
. Use el control deslizante Register OnCommand API Services para habilitar los servicios de API de OnCommand.
. Introduzca la dirección IP, el puerto de servicio y las credenciales de OnCommand API Services.
+
También puede utilizar el cuadro de diálogo Administrar extensiones de proveedor VASA para las siguientes modificaciones:

+
** Para actualizar el registro de los servicios API de OnCommand cuando se produce cualquier cambio en las credenciales.
** Para cancelar el registro de los servicios API de OnCommand cuando ya no necesite el panel vVols.
+
Debe desactivar la casilla de comprobación Register OnCommand API Services para quitar el registro de servicios API de OnCommand para proveedor VASA.



. Haga clic en *aplicar*.
+
El panel vVols muestra las métricas para los almacenes de datos DE ONTAP 9.6 o VERSIONES anteriores de SAN vVols sólo después de que se haya completado el registro de los Servicios de API de OnCommand.



*Información relacionada*

https://mysupport.netapp.com/site/global/dashboard["Soporte de NetApp"]
