---
permalink: configure/task_provision_datastores.html 
sidebar: sidebar 
keywords:  
summary: 'El aprovisionamiento de un almacén de datos crea un contenedor lógico para las máquinas virtuales y sus discos de máquinas virtuales \(VMDK\). Puede aprovisionar un almacén de datos y, a continuación, asociar el almacén de datos a un solo host, a todos los hosts de un clúster o a todos los hosts de un centro de datos.' 
---
= Aprovisione almacenes de datos tradicionales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El aprovisionamiento de un almacén de datos crea un contenedor lógico para las máquinas virtuales y sus discos de máquina virtual (VMDK). Puede aprovisionar un almacén de datos y, a continuación, asociar el almacén de datos a un solo host, a todos los hosts de un clúster o a todos los hosts de un centro de datos.

*Lo que necesitará*

* Para aprovisionar un almacén de datos en una SVM que está conectada directamente a las herramientas de ONTAP, debe haber añadido la SVM a las herramientas de ONTAP con una cuenta de usuario que tiene los privilegios correspondientes, no la cuenta de usuario vsadmin predeterminada o el rol vsadmin.
+
También puede aprovisionar un almacén de datos con un clúster de.

* Debe asegurarse de que los detalles de subred de todas las redes a las que está conectado el host ESXi se hayan introducido en kaminoprefs.xml.
+
Consulte "activación del montaje del almacén de datos en distintas subredes".

* Si utiliza NFS o iSCSI, y la subred es diferente entre los hosts ESXi y el sistema de almacenamiento, la configuración de NFS o iSCSI en el archivo de preferencias kaminoprefs debe incluir máscaras de subred de host ESXi.
+
Este archivo de preferencias también se aplica a la creación de almacenes de datos vVols. Consulte _Enable datastore mount across different subnets_ y _Configure the ONTAP tools preferences files_ para obtener más información.

* Si habilitó VASA Provider y desea especificar perfiles de funcionalidad de almacenamiento para los almacenes de datos de NFS o los almacenes de datos VMFS, debe haber creado uno o varios perfiles de funcionalidad de almacenamiento.
* Para crear un almacén de datos NFSv4.1, debe haber habilitado NFSv4.1 en el nivel de SVM.


La opción *aprovisionar Datastore* permite especificar un perfil de capacidad de almacenamiento para el almacén de datos. Los perfiles de capacidades de almacenamiento ayudan a especificar objetivos de nivel de servicio (SLO) constantes y simplifican el proceso de aprovisionamiento. Es posible especificar un perfil de funcionalidad de almacenamiento solo si se habilitó el proveedor de VASA. Las herramientas de ONTAP para VMware vSphere son compatibles con los siguientes protocolos:

* NFSv3 y NFSv4.1
* VMFS5 y VMFS6
* En la versión vSphere 8,0, el protocolo NVMe/FC es compatible con los almacenes de datos VVOL.


Las herramientas de ONTAP pueden crear un almacén de datos en un volumen NFS o LUN:

* Para un almacén de datos NFS, las herramientas de ONTAP crean un volumen NFS en el sistema de almacenamiento y, a continuación, actualizan las políticas de exportación.
* Para un almacén de datos VMFS, las herramientas de ONTAP crean un volumen nuevo (o utilizan un volumen existente, si seleccionó esa opción) y, a continuación, crean un LUN y un igroup.


[NOTE]
====
* Las herramientas de ONTAP admiten el aprovisionamiento de almacenes de datos de VMFS5 y VMFS6, con un tamaño de volumen y LUN de VMFS máximo de 64 TB, cuando se utilizan con ASA y sistemas AFF aprobados con ONTAP 9.8 y versiones posteriores.
+
En las otras plataformas, el tamaño de LUN máximo admitido es de 16 TB.

* VMware no es compatible con NFSv4.1 con clústeres de almacenes de datos.


====
* Para la autenticación Kerberos, necesitará lo siguiente:
+
** Máquina Windows con Active Directory (AD)
** Servidor de nombres de dominio (DNS)
** Centro de distribución de claves (KDC)
** Sistema de almacenamiento de ONTAP (clúster) con Kerberos configurado
** Host ESXi con Kerberos configurado




Si no se especifica un perfil de funcionalidad de almacenamiento durante el aprovisionamiento, se puede utilizar más adelante la página Storage Mapping para asignar un almacén de datos a un perfil de funcionalidad de almacenamiento. Puede aplicar la configuración de calidad de servicio del almacenamiento, el techo de rendimiento (IOPS máx.) y la planta de rendimiento (IOPS mín.) en archivos de datos VMDK de máquinas virtuales aprovisionados en un almacén de datos respaldado de FlexGroup. La configuración de QoS se puede aplicar a nivel de almacén de datos o en cada máquina virtual haciendo clic con el botón derecho en el almacén de datos. La opción con el botón derecho está disponible solo en esos almacenes de datos o máquinas virtuales de los que se realiza un backup de un almacén de datos de FlexGroup. Una vez que se aplica la calidad de servicio a un almacén de datos, se anulan los ajustes preexistentes de almacén de datos o de calidad de servicio de las máquinas virtuales. La configuración de QoS no se puede aplicar a nivel de almacén de datos ni a un nivel de máquina virtual para almacenes de datos aprovisionados en usuarios de SVM, ya que ONTAP no admite QoS en el nivel de gestión de SVM.

* Pasos*

. Para acceder al asistente de aprovisionamiento de almacenes de datos, se puede utilizar uno de los siguientes métodos:
+
|===


| *Si selecciona de ...* | *Realice lo siguiente...* 


 a| 
Página de inicio de vSphere Client
 a| 
.. Haga clic en *hosts y clústeres*.
.. En el panel de navegación, seleccione el centro de datos donde desea aprovisionar el almacén de datos.
.. Para especificar los hosts para montar el almacén de datos, consulte el paso siguiente.




 a| 
Página de inicio de las herramientas de ONTAP
 a| 
.. Haga clic en *Descripción general*.
.. Haga clic en la ficha *Introducción*.
.. Haga clic en el botón *aprovisionar*.
.. Haga clic en *examinar* para seleccionar el destino en el que aprovisionar el almacén de datos según el paso siguiente.


|===
. Especifique los hosts en los que desea montar el almacén de datos.
+
|===


| *Para que el almacén de datos esté disponible para...* | * Haga esto...* 


 a| 
Todos los hosts de un centro de datos
 a| 
Haga clic con el botón derecho en un centro de datos y seleccione *Herramientas de ONTAP de NetApp* > *aprovisionar almacén de datos*.



 a| 
Todos los hosts de un clúster
 a| 
Haga clic con el botón derecho en un clúster de hosts y seleccione *Herramientas de ONTAP de NetApp* > *aprovisionar almacén de datos*.



 a| 
Un solo host
 a| 
Haga clic con el botón derecho en un host y seleccione *Herramientas ONTAP de NetApp* > *aprovisionar almacén de datos*.

|===
. Complete los campos en el cuadro de diálogo New Datastore para crear el almacén de datos.
+
La mayoría de los campos del cuadro de diálogo son claros y explicativos. En la siguiente tabla se describen algunos de los campos que pueden requerir explicación.

+
|===


| *Sección* | *Descripción* 


 a| 
Generales
 a| 
En la sección General del cuadro de diálogo New Datastore Provisioning se proporcionan opciones para introducir el destino, el nombre, el tamaño, el tipo y el protocolo para el nuevo almacén de datos.

Puede seleccionar el tipo *nfs*, *VMFS* o *vvols* para configurar un almacén de datos. Cuando selecciona el tipo vVols, el protocolo NVMe/FC se vuelve disponible.


NOTE: El protocolo NVMe/FC es compatible con ONTAP 9.91P3 y versiones posteriores.

** NFS: Puede aprovisionar un almacén de datos NFS con los protocolos NFS3 o NFS4,1.
+
Puede seleccionar la opción *Distribuir datos de almacenes de datos a través del clúster de ONTAP* para aprovisionar un volumen de FlexGroup en el sistema de almacenamiento. Al seleccionar esta opción se anula automáticamente la selección de la casilla de verificación *Usar perfil de capacidad de almacenamiento para el aprovisionamiento*.

** VMFS: Puede aprovisionar un almacén de datos VMFS del tipo de sistema de archivos VMFS5 o VMFS6 con los protocolos iSCSI o FC/FCoE.
+

NOTE: Si VASA Provider está habilitado, puede elegir usar los perfiles de funcionalidad de almacenamiento.





 a| 
Autenticación Kerberos
 a| 
Si ha seleccionado NFS 4.1 en la página *General*, seleccione el nivel de seguridad.

La autenticación Kerberos solo es compatible con FlexVols.



 a| 
Sistema de almacenamiento
 a| 
Puede seleccionar uno de los perfiles de capacidad de almacenamiento de la lista si ha seleccionado la opción en la sección General.

** Si va a aprovisionar un almacén de datos de FlexGroup, no es compatible el perfil de funcionalidad de almacenamiento para este almacén de datos. Se facilitan los valores recomendados por el sistema de almacenamiento y la máquina virtual de almacenamiento. Pero puede modificar los valores si es necesario.
** Para la autenticación Kerberos, se muestran los sistemas de almacenamiento habilitados para Kerberos.




 a| 
Los atributos del almacenamiento
 a| 
De forma predeterminada, las herramientas de ONTAP rellenan los valores recomendados para las opciones *Aggregates* y *volumes*. Puede personalizar los valores según sus requisitos. No se admite la selección de agregados en los almacenes de datos FlexGroup, mientras ONTAP gestiona la selección de agregados.

La opción *Space reserve* disponible en el menú *Advanced* también se rellena para obtener resultados óptimos.

(Opcional) puede especificar el nombre del iGroup en el campo *Cambiar nombre del iGroup*.

** Se creará un nuevo iGroup con este nombre si aún no existe ninguno.
** El nombre del protocolo se anexará al nombre del iGroup especificado.
** Si se encuentra un igroup existente con los iniciadores seleccionados, se cambiará el nombre del igroup con el nombre proporcionado y se volverá a utilizar.
** Si no especifica un nombre de igroup, se creará el igroup con el nombre predeterminado.




 a| 
Resumen
 a| 
Es posible revisar el resumen de los parámetros especificados para el almacén de datos nuevo.

El campo «'estilo de volumen» le permite diferenciar el tipo de almacén de datos creado. El «estilo de volumen» puede ser «FlexVol» o «FlexGroup».

|===
+

NOTE: Una FlexGroup que forma parte de un almacén de datos tradicional no se puede reducir por debajo del tamaño existente, pero puede crecer un 120 % como máximo. Las Snapshot predeterminadas están habilitadas en estos volúmenes de FlexGroup.

. En la sección Resumen, haga clic en *Finalizar*.


*Información relacionada*

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Virtual_Storage_Console_for_VMware_vSphere/Datastore_inaccessible_when_volume_status_is_changed_to_offline["Almacén de datos inaccesible cuando el estado del volumen cambia a sin conexión"]

https://docs.netapp.com/us-en/ontap/nfs-admin/ontap-support-kerberos-concept.html["Compatibilidad de ONTAP para Kerberos"]

https://docs.netapp.com/us-en/ontap/nfs-admin/requirements-configuring-kerberos-concept.html["Requisitos para configurar Kerberos con NFS"]

https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/concept_kerberos_realm_services.html["Gestione servicios de dominio de Kerberos con System Manager: ONTAP 9.7 y versiones anteriores"]

https://docs.netapp.com/us-en/ontap/nfs-config/create-kerberos-config-task.html["Habilite Kerberos en una LIF de datos"]

https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.storage.doc/GUID-BDCB7500-72EC-4B6B-9574-CFAEAF95AE81.html["Configure hosts ESXi para la autenticación Kerberos"]
