---
permalink: configure/task_configure_alarm_thresholds.html 
sidebar: sidebar 
keywords:  
summary: Puede utilizar las herramientas de ONTAP para establecer alarmas que le notifiquen cuando los umbrales de volumen y los umbrales agregados alcancen los límites establecidos. 
---
= Configure los umbrales de alarma
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar las herramientas de ONTAP para establecer alarmas que le notifiquen cuando los umbrales de volumen y los umbrales agregados alcancen los límites establecidos.

* Pasos*

. En la página de inicio de las herramientas de ONTAP, haga clic en *Configuración*.
. Haga clic en *Configuración de Unified Appliance*.
. Especifique los valores porcentuales para el campo *umbral casi completo (%)* y el campo *umbral completo (%)* para los umbrales de alarma de volumen y los umbrales de alarma agregados.
+
Al configurar los valores, debe tener en cuenta la siguiente información:

+
** Al hacer clic en *Restablecer*, se restablecen los umbrales a los valores anteriores.
+
Al hacer clic en *Restablecer* no se restablecen los umbrales a los valores predeterminados del 80 por ciento para "'casi lleno'" y del 90 por ciento para "'lleno'".

** Existen dos formas de establecer los valores:
+
*** Puede utilizar las flechas arriba y abajo junto a los valores para ajustar los valores de umbral.
*** Puede deslizar las flechas en la barra de traza por debajo de los valores para ajustar los valores de umbral.


** El valor más bajo que se puede establecer para el campo *umbral completo (%)* para volúmenes y agregados es del 6%.


. Después de especificar los valores necesarios, haga clic en *aplicar*.
+
Debe hacer clic en *aplicar* tanto para la alarma de volumen como para la alarma agregada.


