---
permalink: configure/task_discover_storage_systems_and_hosts.html 
sidebar: sidebar 
keywords:  
summary: 'Cuando se ejecuta por primera vez Virtual Storage Console \(VSC\) en una instancia de vSphere Client, VSC detecta los hosts ESXi, sus LUN y exportaciones NFS y los sistemas de almacenamiento de NetApp a los que pertenecen estas LUN y exportaciones.' 
---
= Detectar sistemas de almacenamiento y hosts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando se ejecuta Virtual Storage Console (VSC) en una instancia de vSphere Client, VSC detecta los hosts ESXi, sus LUN y exportaciones NFS y los sistemas de almacenamiento de NetApp que poseen esas LUN y exportaciones.

*Lo que necesitará*

* Todos los hosts ESXi deben estar encendidos y conectados.
* Todas las máquinas virtuales de almacenamiento que se vayan a detectar deben estar en ejecución y cada nodo del clúster debe tener al menos una LIF de datos configurada para el protocolo de almacenamiento en uso (NFS, iSCSI, FC o NVMe/FC).


*Acerca de esta tarea*

Puede detectar nuevos sistemas de almacenamiento o actualizar información sobre los sistemas de almacenamiento existentes para obtener la información más reciente sobre la configuración y la capacidad en cualquier momento. También puede modificar las credenciales que utiliza VSC para iniciar sesión en los sistemas de almacenamiento.

Al detectar los sistemas de almacenamiento de, VSC recopila información de los hosts ESXi gestionados por la instancia de vCenter Server.

* Pasos*

. En la página Home de vSphere Client, seleccione *hosts and Clusters*.
. Haga clic con el botón derecho en el centro de datos requerido y seleccione *Herramientas de ONTAP de NetApp* > *Actualizar datos de host y almacenamiento* .
+
VSC muestra un cuadro de diálogo Confirmar que le informa de que esta acción reiniciará la detección de todos los sistemas de almacenamiento conectados, y puede demorar varios minutos. ¿Desea continuar?

. Haga clic en *YES*.
. Seleccione las controladoras de almacenamiento detectadas que tengan el estado `Authentication Failure`, Y, a continuación, haga clic en *ACCIONES* > *Modificar*.
. Rellene la información necesaria en el cuadro de diálogo *Modificar sistema de almacenamiento*.
. Repita los pasos 4 y 5 para todas las controladoras de almacenamiento con `Authentication Failure` estado.


Una vez completado el proceso de detección, realice lo siguiente:

* Utilice VSC para configurar los ajustes del host ESXi para los hosts que muestran el icono Alert en la columna Adapter Settings, la columna MPIO Settings o la columna NFS Settings.
* Proporcione las credenciales del sistema de almacenamiento.

