---
permalink: configure/task_enable_datastore_mounting_across_different_subnets.html 
sidebar: sidebar 
keywords:  
summary: 'Si utiliza iSCSI o NFS y la subred es diferente entre los hosts ESXi y el sistema de almacenamiento, debe modificar los archivos de preferencias de las herramientas de ONTAP para VMware vSphere. Si no modifica el archivo de preferencias, el aprovisionamiento del almacén de datos genera errores porque Virtual Storage Console \(VSC\) no puede montar el almacén de datos.' 
---
= Habilite el montaje del almacén de datos en diferentes subredes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si utiliza iSCSI o NFS y la subred es diferente entre los hosts ESXi y el sistema de almacenamiento, debe modificar los archivos de preferencias de las herramientas de ONTAP para VMware vSphere. Si no modifica el archivo de preferencias, el aprovisionamiento del almacén de datos genera errores porque Virtual Storage Console (VSC) no puede montar el almacén de datos.

*Acerca de esta tarea*

Cuando se produce un error en el aprovisionamiento del almacén de datos, las herramientas de ONTAP para VMware vSphere registran los siguientes mensajes de error:

'No se puede continuar. No se encontraron direcciones ip al hacer referencia cruzada a las direcciones ip del kernel y a las direcciones en la controladora. No se pudo encontrar una red coincidente con el volumen de montaje NFS en estos hosts.'

* Pasos*

. Inicie sesión en la instancia de vCenter Server.
. Inicie la consola de mantenimiento con la máquina virtual unificada del dispositivo.
+
link:../manage/reference_maintenance_console_of_ontap_tools_for_vmware_vsphere.html["Consola de mantenimiento de herramientas de ONTAP para VMware vSphere"]

. Introduzca `4` Para acceder a la opción Soporte y diagnóstico.
. Introduzca `2` Para acceder a la opción Access Diagnostic Shell (Shell de diagnóstico de acceso).
. Introduzca `vi /opt/netapp/vscserver/etc/kamino/kaminoprefs.xml` para actualizar la `kaminoprefs.xml` archivo.
. Actualice el `kaminoprefs.xml` archivo.
+
|===


| *Si utiliza...* | * Haga esto...* 


 a| 
ISCSI
 a| 
Cambie el valor de la clave de entrada `default.allow.iscsi.mount.networks` Desde TODO hasta el valor de las redes de host ESXi.



 a| 
NFS
 a| 
Cambie el valor de la clave de entrada `default.allow.nfs.mount.networks` Desde TODO hasta el valor de las redes de host ESXi.

|===
+
El archivo de preferencias incluye valores de ejemplo para estas claves de entrada.

+

NOTE: El valor «'TODOS'» no significa todas las redes. El valor «'ALL'» permite utilizar todas las redes coincidentes entre el host y el sistema de almacenamiento para montar almacenes de datos. Cuando se especifican redes host, puede habilitar el montaje solo en las subredes especificadas.

. Guarde y cierre el `kaminoprefs.xml` archivo.

