---
permalink: configure/task_add_storage_systems.html 
sidebar: sidebar 
keywords:  
summary: 'Puede añadir manualmente el sistema de almacenamiento a Virtual Storage Console \(VSC\).' 
---
= Añada sistemas de almacenamiento a VSC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede añadir manualmente el sistema de almacenamiento a Virtual Storage Console (VSC).

*Acerca de esta tarea*

Cada vez que inicia Virtual Storage Console (VSC) o selecciona la opción *REDISCOVER All*, VSC detecta automáticamente los sistemas de almacenamiento disponibles.

* Pasos*

. Añada un sistema de almacenamiento a VSC mediante la página de inicio de las herramientas de ONTAP:
+
** Haga clic en *sistemas de almacenamiento* > *Agregar*.
** Haga clic en *Descripción general* > *Introducción* y, a continuación, haga clic en el botón *AGREGAR* en Agregar sistema de almacenamiento.


. En el cuadro de diálogo *Add Storage System*, introduzca la dirección IP de administración y las credenciales de ese sistema de almacenamiento.
+
También puede añadir sistemas de almacenamiento con la dirección IPv6 del clúster o SVM. También puede cambiar los valores predeterminados para TLS y el número de puerto en este cuadro de diálogo.

+
Cuando añade almacenamiento desde la página VSC Storage System, también debe especificar la instancia de vCenter Server donde se ubicará el almacenamiento. El cuadro de diálogo Add Storage System proporciona una lista desplegable de las instancias disponibles de vCenter Server. VSC no muestra esta opción si añade almacenamiento a un centro de datos que ya está asociado a una instancia de vCenter Server.

. Haga clic en *Aceptar* después de haber añadido toda la información necesaria.

