---
permalink: configure/task_enable_vasa_provider_for_configuring_virtual_datastores.html 
sidebar: sidebar 
keywords:  
summary: 'Las herramientas de ONTAP para VMware vSphere tienen habilitada la funcionalidad de proveedor de VASA de forma predeterminada. Puede configurar almacenes de datos VMware Virtual Volumes \(vVols\) con los perfiles de capacidad de almacenamiento necesarios para cada almacén de datos vVols.' 
---
= Habilite VASA Provider para configurar almacenes de datos virtuales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las herramientas de ONTAP para VMware vSphere tienen habilitada la funcionalidad de proveedor de VASA de forma predeterminada. Puede configurar almacenes de datos VMware Virtual Volumes (vVols) con perfiles de capacidad de almacenamiento necesarios para cada almacén de datos vVols.

*Lo que necesitará*

* Debe haber configurado la instancia de vCenter Server y ESXi.
* Debe haber implementado las herramientas de ONTAP .


*Acerca de esta tarea*

Si la funcionalidad del proveedor VASA está deshabilitada antes de actualizar a la versión 9.7.1 de las herramientas de ONTAP , la funcionalidad del proveedor VASA permanece deshabilitada después de la actualización. Esta versión le permite habilitar la función de replicación vVols para almacenes de datos vVols.

* Pasos*

. Inicie sesión en la interfaz de usuario web de VMware vSphere.
. En vSphere Client, haga clic en *Menú* > *Consola de herramientas ONTAP*.
. Haga clic en *Configuración*.
. Haga clic en *Administrar capacidades* en la ficha Configuración administrativa.
. En el cuadro de diálogo gestionar funcionalidades, seleccione la extensión VASA Provider para habilitar.
. Si desea utilizar la capacidad de replicación para almacenes de datos vVols, utilice el botón de alternar *Activar replicación vVols*.
. Introduzca la dirección IP de las herramientas de ONTAP y la contraseña del administrador y, a continuación, haga clic en *aplicar*.
+

NOTE: Si el estado del proveedor VASA aparece como "'fuera de línea'" incluso después de habilitar la extensión del proveedor VASA, compruebe el archivo /var/log/vmware/vmware-sps/sps.log en busca de errores de conexión con VASA Provider o reinicie el servicio "'vmware-sps'".



Si utiliza ONTAP 9.6 o clústeres anteriores, debe registrar los servicios API de OnCommand con VASA Provider para obtener detalles de los almacenes de datos vVols y los equipos virtuales que se utilizan en los informes DE almacenes de datos SAN vVols VM y SAN vVols. Sin embargo, si utiliza ONTAP 9.7 o una versión posterior, no es necesario que registre los servicios API de OnCommand con el proveedor VASA.
