---
permalink: configure/task_create_storage_capability_profiles.html 
sidebar: sidebar 
keywords:  
summary: Puede usar herramientas de ONTAP para crear manualmente perfiles de funcionalidad de almacenamiento, generar automáticamente un perfil según las capacidades de un almacén de datos o modificar un perfil para cumplir sus requisitos. 
---
= Crear perfiles de funcionalidad del almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede usar herramientas de ONTAP para crear manualmente perfiles de funcionalidad de almacenamiento, generar automáticamente un perfil según las capacidades de un almacén de datos o modificar un perfil para cumplir sus requisitos.

*Lo que necesitará*

Registró la instancia del proveedor de VASA con las herramientas de ONTAP para VMware vSphere.

Después de configurar un perfil, puede editar el perfil según sea necesario.

* Pasos*

. En la página de inicio de herramientas de ONTAP, haga clic en *Políticas y perfiles*.
. Cree un perfil o edite uno existente, según sea necesario:
+
|===


| *Si quiere...* | * Haga esto...* 


 a| 
Cree un perfil
 a| 
Haga clic en *CREAR*.



 a| 
Edite un perfil existente
 a| 
Haga clic en el perfil que desea modificar desde los perfiles que aparecen en la página *Perfiles de capacidad de almacenamiento*.

|===
+

NOTE: Para ver los valores asociados con un perfil existente, puede hacer clic en el nombre del perfil en la página Storage Capabilities Profile. A continuación, VASA Provider muestra la página Summary para ese perfil.

. Desde *New Datastore* > *Storage Systems*, haz clic en *Create storage capacity profile*.
+
Recibe el siguiente mensaje para confirmar la salida de la ventana del almacén de datos.

+
_Esto eliminará los datos introducidos al cerrar el flujo de trabajo actual y abrirá el flujo de trabajo Crear perfil de capacidad de almacenamiento. ¿Desea continuar?_

. Haga clic en *SÍ* para abrir la ventana Crear perfil de capacidad de almacenamiento.
. Complete las páginas del asistente Crear perfil de capacidad de almacenamiento para configurar un perfil o editar valores para modificar un perfil existente.
+
La mayoría de los campos en este asistente son claros y explicativos. En la siguiente tabla se describen algunos de los campos que pueden requerir explicación.

+
|===


| *Campo* | *Explicación* 


 a| 
Identificación de múltiples perfiles
 a| 
Puede usar el campo *Descripción* en la pestaña Nombre y Descripción para describir el propósito del perfil de capacidad de almacenamiento (SCP). Proporcionar una buena descripción es útil porque es una buena práctica configurar diferentes perfiles basados en las aplicaciones que se utilizan.

Por ejemplo, una aplicación vital para el negocio requiere un perfil con capacidades que admitan un rendimiento superior, como la plataforma AFF y ASA. Un almacén de datos que se usa para pruebas o entrenamiento puede usar un perfil con una plataforma Flash Array Hybrid de menor rendimiento y para habilitar todas las funcionalidades de eficiencia del almacenamiento y la organización en niveles para controlar los costes.
La combinación del tipo de plataforma y el indicador asimétrico determina el tipo de SCPs. Por ejemplo: Platinum_ASA_A, Platinum_ASA_C, Platinum_AFF_A, Platinum_AFF_C.

Si ha habilitado el modo «"vinculado"» para vCenter Server, debe seleccionar la instancia de vCenter Server para la cual desea crear el perfil de funcionalidad de almacenamiento.



 a| 
Plataforma
 a| 
A partir de las herramientas de ONTAP para VMware vSphere 9,13, puede crear perfiles de funcionalidades de almacenamiento mediante una combinación de los siguientes elementos:

.. Tipo de plataforma: Rendimiento, capacidad y cabina flash híbrida
.. Marca asimétrica: Indica el estado optimizado para SAN (All SAN Array) del sistema de almacenamiento.
+
*** Cuando el tipo de plataforma es *Performance* y el indicador asimétrico es *TRUE*, considera el sistema de almacenamiento del tipo AFF-A.
*** Cuando el tipo de plataforma es *Rendimiento* y el indicador asimétrico es *Falso*, considera el sistema de almacenamiento del tipo ASA-A.
*** Cuando el tipo de plataforma es *Capacity* y el indicador asimétrico es *True*, considera el sistema de almacenamiento del tipo AFF-C.
*** Cuando el tipo de plataforma es *Flash hybrid array* y el indicador asimétrico es NA, considera el sistema de almacenamiento del tipo FAS




Las opciones de las pantallas siguientes se actualizan en función de la selección del tipo de sistema de almacenamiento.



 a| 
Protocolo
 a| 
Puede seleccionar entre los protocolos disponibles que aparecen en la lista según la plataforma seleccionada para el sistema de almacenamiento. Al configurar los equipos virtuales, puede configurar políticas de almacenamiento de los equipos virtuales con el perfil de capacidad de almacenamiento y el campo de protocolo filtra los almacenes de datos según un protocolo específico. El campo 'any' le permite trabajar con todos los protocolos.



 a| 
Rendimiento
 a| 
Puede establecer políticas de calidad de servicio tradicionales para el sistema de almacenamiento mediante la pestaña rendimiento.

** Al seleccionar *Ninguno*, se aplica una política QoS sin límite (infinito) a un VVol de datos.
** Al seleccionar *Grupo de políticas QoS*, se aplica una política QoS tradicional a un VVol.
+
Puede establecer el valor para *Max IOPS* y *Min IOPS*, lo que le permite utilizar la funcionalidad QoS. Si selecciona Infinite IOPS, el campo Max IOPS está deshabilitado. Cuando se aplica a un almacén de datos tradicional, se crea una política de calidad de servicio con un valor «Max IOPS» y se asigna a un volumen FlexVol. Cuando se utiliza con un almacén de datos vVols, se crea una política de calidad de servicio con los valores Max IOPS y Min IOPS para cada almacén de datos vVols.

+
*NOTA*:

+
*** El valor máximo de IOPS y el valor mínimo de IOPS también se pueden aplicar al volumen FlexVol para un almacén de datos tradicional.
*** Debe asegurarse de que las métricas de rendimiento no se establezcan por separado en el nivel de máquina virtual de almacenamiento (SVM), de un nivel de agregado o de un volumen de FlexVol.






 a| 
Atributos de almacenamiento
 a| 
Los atributos de almacenamiento que se pueden habilitar en esta pestaña dependen del tipo de almacenamiento que se seleccione en la pestaña Personality.

** Si selecciona almacenamiento híbrido en la cabina flash, puede configurar la reserva de espacio (gruesa o fina), habilitar la deduplicación, la compresión y el cifrado.
+
El atributo de organización en niveles está deshabilitado porque este atributo no se aplica al almacenamiento híbrido de cabina flash.

** Si selecciona el almacenamiento de AFF, puede habilitar el cifrado y la organización en niveles.
+
La deduplicación y la compresión están habilitadas de forma predeterminada en el almacenamiento de AFF y no se pueden deshabilitar.

** Si selecciona Almacenamiento de ASA, puede habilitar el cifrado y la organización en niveles.
+
La deduplicación y la compresión están habilitadas de forma predeterminada para el almacenamiento de ASA y no se pueden deshabilitar.

+
El atributo de organización en niveles permite el uso de volúmenes que forman parte de un agregado habilitado para FabricPool (compatible con VASA Provider para sistemas AFF con ONTAP 9.4 y versiones posteriores). Puede configurar una de las siguientes directivas para el atributo de organización en niveles:

** None: Impide que se muevan datos de volúmenes al nivel de capacidad
** Snapshot: Mueve los bloques de datos de usuario de copias Snapshot de volumen que no están asociadas con el sistema de archivos activo al nivel de capacidad


|===
. Revise sus selecciones en la página Resumen y, a continuación, haga clic en *Aceptar*.
+
Después de crear un perfil, puede volver a la página Storage Mapping para ver qué perfiles coinciden con qué almacenes de datos.


