---
permalink: manage/concept_virtual_storage_console_reports.html 
sidebar: sidebar 
keywords:  
summary: Puede utilizar el menú de informes de la consola de herramientas de ONTAP para ver informes predefinidos de todos los almacenes de datos gestionados por una instancia de VSC seleccionada en una instancia concreta de vCenter Server. Puede realizar operaciones como ordenar y exportar informes. 
---
= Descripción general de los informes de vVols y almacenes de datos de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el menú * Reports* de la consola de herramientas de ONTAP para ver informes predefinidos para todos los almacenes de datos gestionados por una instancia de VSC seleccionada en un vCenter Server en particular. Puede realizar operaciones como ordenar y exportar informes.

Los informes muestran información detallada sobre los almacenes de datos y las máquinas virtuales, lo que permite revisar e identificar problemas potenciales con los almacenes de datos y las máquinas virtuales en vCenter Server

Es posible ver, ordenar y exportar informes.

Virtual Storage Console (VSC) ofrece los siguientes informes predefinidos:

* Informe del almacén de datos
* Informe de máquinas virtuales
* Informe de almacén de datos de vVols
* Informe de máquina virtual vVols




== Informes del almacén de datos

Los informes de almacenes de datos, proporcionan información detallada sobre los almacenes de datos tradicionales y las máquinas virtuales que se crean en estos almacenes de datos.

La consola tradicional le permite revisar e identificar problemas potenciales con los almacenes de datos y las máquinas virtuales en vCenter Server. Es posible ver, ordenar y exportar informes. VCenter Server proporciona el informe de datos para los almacenes de datos tradicionales y las máquinas virtuales. Sin embargo, debido a la introducción de la compatibilidad con almacenes de datos respaldados por FlexGroup, algunas métricas como la latencia, el rendimiento y las IOPS se obtienen a través de ONTAP.


NOTE: No se admite la supervisión de archivos para almacenes de datos FlexGroup configurados en máquinas virtuales de almacenamiento directo (SVM).

El almacén de datos ofrece los siguientes informes predefinidos:

* Informe del almacén de datos
* Informe de máquinas virtuales


*Informe de Datastore*

El menú Datastore Report ofrece información sobre los siguientes parámetros para los almacenes de datos:

* Nombre del almacén de datos
* Tipo de almacén de datos: NFS o VMFS
* Estilo de volumen
+
El estilo de los volúmenes puede ser un volumen de FlexVol o un volumen de FlexGroup.

* Espacio libre
* El espacio utilizado
* Espacio total
* Porcentaje de espacio utilizado
* Porcentaje de espacio disponible
* IOPS
+
El informe muestra la tasa de IOPS del almacén de datos.

* Latencia
+
El informe muestra la información de latencia del almacén de datos.

+
También puede verificar la hora en la que se generó el informe. El menú Datastore Report le permite organizar el informe según sus necesidades y, a continuación, exportar el informe organizado mediante el botón *Exportar a CSV*. Los nombres de los almacenes de datos del informe son enlaces que van a la pestaña Monitor del almacén de datos seleccionado, donde se pueden ver las métricas de rendimiento del almacén de datos.



*Informe de máquina virtual*

El menú Virtual Machine Report ofrece las métricas de rendimiento de todas las máquinas virtuales que utilizan almacenes de datos aprovisionados por VSC para una instancia seleccionada de vCenter Server. Las métricas de máquina virtual que se muestran en los informes de máquinas virtuales son datos históricos que se recopilan cada 30 minutos para las máquinas virtuales de almacenes de datos tradicionales. Las opciones "última actualización" y "próxima actualización" se agregan a la tabla para proporcionar detalles sobre cuándo se recopilaron los datos y cuándo será la siguiente recopilación de datos.

* Nombre de la máquina virtual
* Nombre del almacén de datos
* Estilo de volumen
+
El estilo de los volúmenes puede ser un volumen de FlexVol o un volumen de FlexGroup.

* Origen
+
El origen para recopilar detalles de la máquina virtual puede ser ONTAP o vCenter Server.

* Latencia
+
El informe muestra la latencia de las máquinas virtuales en todos los almacenes de datos asociados con las máquinas virtuales.

* IOPS
* Rendimiento
* Capacidad comprometida
+
El informe muestra el valor de la capacidad comprometida de una máquina virtual.

* Host
+
El informe muestra los sistemas host en los que está disponible la máquina virtual.

* Siempre activo
+
El informe muestra la hora durante la que se enciende la máquina virtual y está disponible en un host ESXi.

* Estado de alimentación
+
El informe muestra si la máquina virtual está encendida o apagada.



Cada nombre de máquina virtual del informe es un enlace a la ficha Monitor de la máquina virtual seleccionada. Puede ordenar el informe de la máquina virtual según sus necesidades, exportar el informe en un archivo .CSV y guardar el informe en el sistema local. La Marca de hora del informe también se añade al informe guardado.

Para máquinas virtuales a las que se realizan backups de FlexGroup Volumes, cuando se enciende la nueva máquina virtual, se registran archivos para la supervisión en ONTAP. Las métricas históricas de latencia, rendimiento e IOPS se obtienen cuando se accede a los informes de VM desde ONTAP.



== Informes de vVols

Los informes vVols muestran información detallada sobre los almacenes de datos VMware Virtual Volumes (vVols) y las máquinas virtuales que se crean en estos almacenes de datos. La consola vVols le permite revisar e identificar problemas potenciales con los almacenes de datos vVols y los equipos virtuales en vCenter Server.

Puede ver, organizar y exportar informes. Los datos del informe de los almacenes de datos vVols y las máquinas virtuales son proporcionados por ONTAP junto con los servicios API de OnCommand.

VVols ofrece los siguientes informes predefinidos:

* Informe de almacén de datos de vVols
* Informe de vVols VM


*VVols Datastore Report*

El menú vVols Datastore Report ofrece información acerca de los siguientes parámetros para los almacenes de datos:

* Nombre del almacén de datos vVols
* Espacio libre
* El espacio utilizado
* Espacio total
* Porcentaje de espacio utilizado
* Porcentaje de espacio disponible
* IOPS
* Las métricas de rendimiento de latencia están disponibles para los almacenes de datos vVols basados en NFS en ONTAP 9.8 y versiones posteriores. También puede verificar la hora en la que se generó el informe. El menú Informe de almacenes de datos vVols le permite organizar el informe según sus necesidades y, a continuación, exportar el informe organizado mediante el botón *Exportar a CSV*. Cada nombre de almacén DE datos DE SAN vVols del informe es un enlace que se desplaza a la pestaña Monitor del almacén de datos DE SAN vVols seleccionado, que se puede utilizar para ver las métricas de rendimiento.


*Informe de la máquina virtual de vVols*

El menú de informe de resumen de máquina virtual vVols proporciona las métricas de rendimiento de todas las máquinas virtuales que utilizan los almacenes de datos SAN vVols aprovisionados por VASA Provider para ONTAP para un vCenter Server seleccionado. Las métricas de máquina virtual que se muestran en los informes de VM son datos históricos que se recopilan cada 10 minutos para las máquinas virtuales en almacenes de datos vVols. Se agregan "Last Refresh Time" y "Next Refresh time" a la tabla para proporcionar información sobre cuándo se recopilaron los datos y cuándo será la próxima recopilación de datos.

* Nombre de la máquina virtual
* Capacidad comprometida
* Siempre activo
* IOPS
* Rendimiento
+
El informe muestra si la máquina virtual está encendida o apagada.

* Espacio lógico
* Host
* Estado de alimentación
* Latencia
+
El informe muestra la latencia de las máquinas virtuales en todos los almacenes de datos vVols asociados con las máquinas virtuales.



Cada nombre de máquina virtual del informe es un enlace a la ficha Monitor de la máquina virtual seleccionada. Puede organizar el informe de la máquina virtual según sus necesidades y exportar el informe en `.CSV` formatee y guarde el informe en el sistema local. La fecha/hora del informe se adjunta al informe guardado.
