---
permalink: manage/task_mount_datastores_on_host.html 
sidebar: sidebar 
keywords:  
summary: El montaje de un almacén de datos permite acceder al almacenamiento a hosts adicionales. El almacén de datos se puede montar en los hosts adicionales después de añadir los hosts al entorno de VMware. 
---
= Monte el almacén de datos en hosts adicionales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El montaje de un almacén de datos permite acceder al almacenamiento a hosts adicionales. El almacén de datos se puede montar en los hosts adicionales después de añadir los hosts al entorno de VMware.

*Lo que necesitará*

Debe asegurarse de que se hayan introducido en la los detalles de subred de todas las redes a las que está conectado el servidor ESXi `Kaminoprefs.xml`.

Consulte la sección Habilitar el montaje del almacén de datos en diferentes subredes.

* Pasos*

. En la página Home de vSphere Client, haga clic en *hosts and Clusters*.
. En el panel de navegación, seleccione el centro de datos que contiene el host.
. Repita el paso 2 para cualquier host adicional.
. Haga clic con el botón derecho en el host y seleccione *ONTAP tools* de NetApp > *Mount datastores*.
. Seleccione los almacenes de datos que desea montar y, a continuación, haga clic en *Aceptar*.

