---
permalink: manage/task_monitor_datastores_using_the_traditional_dashboard.html 
sidebar: sidebar 
keywords:  
summary: Puede supervisar los almacenes de datos tradicionales y las máquinas virtuales mediante la consola tradicional de las herramientas de ONTAP. Los datos de la consola le permiten analizar el uso del almacén de datos y realizar acciones correctivas para evitar que las máquinas virtuales se ejecuten en restricciones relacionadas con el espacio. 
---
= Analice datos de rendimiento con la consola tradicional
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede supervisar los almacenes de datos tradicionales y las máquinas virtuales mediante la consola tradicional de las herramientas de ONTAP. Los datos de la consola le permiten analizar el uso del almacén de datos y realizar acciones correctivas para evitar que las máquinas virtuales se ejecuten en restricciones relacionadas con el espacio.

*Lo que necesitará*

Debe seleccionar la opción *Activar control de E/S de almacenamiento y recopilación de estadísticas* o *Desactivar control de E/S de almacenamiento pero habilitar recopilación de estadísticas* en el cuadro de diálogo Configurar control de E/S de almacenamiento. Solo es posible habilitar Storage I/o Control si tiene la licencia Enterprise Plus de VMware.

https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.resmgmt.doc/GUID-BB5D9BAB-9E0E-4204-A76A-54634CD8AD51.html["Documentación de VMware vSphere: Habilitar Storage I/o Control"]

La consola tradicional muestra métricas de IOPS, espacio utilizado, latencia y capacidad comprometida que se obtienen en vCenter Server. ONTAP proporciona indicadores de ahorro de espacio agregado a la consola tradicional. Puede ver el ahorro de espacio para un agregado específico. Estos parámetros de rendimiento le permiten identificar cuellos de botella de rendimiento en el entorno virtual y realizar acciones correctivas para resolver los problemas.


NOTE: No se admite la supervisión de archivos para almacenes de datos FlexGroup configurados en máquinas virtuales de almacenamiento directo (SVM).

La consola tradicional de las herramientas de ONTAP le permite ver almacenes de datos NFS o almacenes de datos VMFS. Es posible hacer clic en un almacén de datos para desplazarse a la vista de detalles del almacén de datos que proporciona la instancia de vCenter Server para ver y corregir cualquier problema con los almacenes de datos en vCenter Server.

* Pasos*

. En la página de inicio de vSphere Client, haga clic en *Herramientas de ONTAP para VMware vSphere*.
. Seleccione el vCenter Server requerido con el selector *INSTANCE* para ver los almacenes de datos.
. Haga clic en *Descripción general > Panel tradicional*.
+
El portlet datastores proporciona los siguientes detalles:

+
** El número de almacenes de datos tradicionales junto con sus métricas de rendimiento que gestiona VSC en su instancia de vCenter Server
** Los cinco almacenes de datos principales según los parámetros de uso y rendimiento de los recursos que se pueden modificar, si es necesario, puede cambiar la lista de los almacenes de datos según el espacio utilizado, IOPS o latencia y el orden requerido.


+
El portlet Máquinas virtuales proporciona los siguientes detalles:

+
** Número de máquinas virtuales que utilizan almacenes de datos de NetApp en vCenter Server
** Las cinco máquinas virtuales más importantes basadas en capacidad, latencia, IOPS, rendimiento y tiempo activo prometidos
+
Los datos de IOPS y rendimiento del portlet Máquinas virtuales solo están disponibles para almacenes de datos creados en volúmenes respaldados por FlexGroup.




