---
permalink: manage/task_monitor_vvols_datastores_and_virtual_machines_using_vvols_dashboard.html 
sidebar: sidebar 
keywords:  
summary: 'Puede supervisar el rendimiento y ver los cinco almacenes de datos PRINCIPALES SAN y NAS VMware Virtual Volumes \(vVols\) en vCenter Server según los parámetros que seleccione utilizando el panel vVols de las herramientas ONTAP.' 
---
= Analice los datos de rendimiento con el panel vVols
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede supervisar el rendimiento y ver los cinco almacenes de datos PRINCIPALES SAN y NAS VMware Virtual Volumes (vVols) en vCenter Server según los parámetros que seleccione con la consola vVols de las herramientas ONTAP.

*Lo que necesitará*

* Debe utilizar ONTAP 9,7 o posterior para el sistema de almacenamiento.


Los datos de IOPS que proporciona ONTAP se redondean y se muestran en el panel de vVols. Puede haber una diferencia entre el valor de IOPS real que proporciona ONTAP y el valor de IOPS que se muestra en el panel de vVols. Las herramientas de ONTAP proporcionan supervisión del rendimiento para almacenes de datos vVols basados en NFS.

* Los datos del panel de vVols se actualizan periódicamente, con un intervalo de 10 minutos.
* Si ha añadido, modificado o eliminado un sistema de almacenamiento de la instancia de vCenter Server, es posible que no note ningún cambio en los datos de la consola de vVols durante algún tiempo.
* El valor total de IOPS que se muestra en el portlet Overview de la consola vVols no es un valor acumulativo de IOPS de lectura y valor de IOPS de escritura.
* Los vVols de datos basados en NFS aprovisionados con ONTAP 9.8 y versiones posteriores se registran automáticamente para supervisar el rendimiento en el panel vVols.


* Pasos*

. En la página de inicio de vSphere Client, haga clic en *Herramientas de ONTAP*.
. Seleccione el vCenter Server requerido con el selector *INSTANCE* para ver los almacenes de datos.
. Haga clic en *Overview > vVols Dashboard*.
+
El portlet datastores proporciona los siguientes detalles:

+
** El número de almacenes de datos vVols gestionados por VASA Provider en la instancia de vCenter Server
** Los cinco almacenes de datos vVols principales según el uso de recursos y los parámetros de rendimiento, puede cambiar la lista de los almacenes de datos en función del espacio utilizado, las IOPS o la latencia y del orden necesario.


. Vea los detalles de las máquinas virtuales con el portlet Máquinas virtuales.
+
El portlet Máquinas virtuales proporciona los siguientes detalles:

+
** Número de máquinas virtuales que utilizan almacenes de datos ONTAP en vCenter Server
** Las cinco máquinas virtuales más importantes basadas en IOPS, latencia, rendimiento, capacidad dedicada, tiempo activo, Y espacio lógico puede personalizar cómo se enumeran las cinco máquinas virtuales principales en el panel de control de vVols.






== Requisitos de datos del panel de vVols

Debe verificar algunos requisitos importantes del panel vVols para mostrar detalles dinámicos de los almacenes de datos y las máquinas virtuales de VMware Virtual Volumes (vVols).

La siguiente tabla muestra una descripción general de lo que debe comprobar si el panel de vVols no muestra las métricas de rendimiento para los almacenes de datos DE SAN vVols aprovisionados y las máquinas virtuales.

|===
| *Consideraciones* | *Descripción* 


 a| 
Sistema de almacenamiento
 a| 
* Utiliza ONTAP 9,7 o posterior.
* Se utilizan credenciales adecuadas para el sistema de almacenamiento.
* El sistema de almacenamiento es activo y accesible.
* La máquina virtual seleccionada debe utilizar al menos un almacén de datos vVols, y las operaciones de I/o se están ejecutando en el disco de la máquina virtual.


|===