---
permalink: manage/task_change_the_administrative_password.html 
sidebar: sidebar 
keywords:  
summary: Puede cambiar la contraseña de administrador de las herramientas de ONTAP después de la implementación mediante la consola de mantenimiento. 
---
= Cambie la contraseña del administrador
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede cambiar la contraseña de administrador de las herramientas de ONTAP después de la implementación mediante la consola de mantenimiento. La contraseña caduca después de 90 días.

* Pasos*

. Desde vCenter Server, abra una consola a las herramientas ONTAP.
. Inicie sesión como el usuario de mantenimiento.
. Introduzca `1` En la consola de mantenimiento para seleccionar Configuración de la aplicación.
. Introduzca `6` Para seleccionar *Cambiar la contraseña de usuario de administrador*.
. Introduzca una contraseña con un mínimo de ocho caracteres y un máximo de 30 caracteres. La contraseña debe contener como mínimo un carácter superior, uno inferior, un dígito y un carácter especial. La advertencia de caducidad de la contraseña se muestra después de 75 días de restablecer la contraseña. La nueva contraseña no puede ser la misma que la última contraseña utilizada.
+
Si no sigue las recomendaciones de contraseña, la opción de la consola de mantenimiento se limita a cambiar la contraseña. Cuando la contraseña haya caducado, se le pedirá que cambie la contraseña.

. Introduzca `y` en el cuadro de diálogo de confirmación.

